21: [
  {q:"Area of triangle with base 10 and height 6?",a:"30",b:"60",c:"20",d:"15",ans:"A",diff:"Easy"},
  {q:"Area of equilateral triangle with side 6 cm?",a:"9*sqrt(3)",b:"18",c:"6*sqrt(3)",d:"36",ans:"A",diff:"Easy"},
  {q:"In right triangle legs 3 and 4. Hypotenuse?",a:"5",b:"7",c:"6",d:"8",ans:"A",diff:"Easy"},
  {q:"Perimeter of equilateral triangle with side 7?",a:"21",b:"14",c:"28",d:"35",ans:"A",diff:"Easy"},
  {q:"Sum of angles of a triangle?",a:"180",b:"360",c:"90",d:"270",ans:"A",diff:"Easy"},
  {q:"Area using Heron's formula: s=(a+b+c)/2. Area = sqrt(s(s-a)(s-b)(s-c)). For 3 4 5?",a:"6",b:"12",c:"7.5",d:"10",ans:"A",diff:"Easy"},
  {q:"In isosceles triangle two sides = 5 base = 6. Height?",a:"4",b:"3",c:"5",d:"6",ans:"A",diff:"Easy"},
  {q:"Exterior angle of triangle equals?",a:"Sum of two non-adjacent interior angles",b:"All three interior angles",c:"Adjacent interior angle",d:"180 degrees",ans:"A",diff:"Easy"},
  {q:"Median divides triangle into two triangles of?",a:"Equal area",b:"Equal sides",c:"Similar shape",d:"Different areas",ans:"A",diff:"Easy"},
  {q:"In triangle sum of any two sides > third side. For sides 5 7 x: x must be < ?",a:"12",b:"7",c:"5",d:"2",ans:"A",diff:"Easy"},
  {q:"Area of triangle with sides 5 12 13?",a:"30",b:"60",c:"25",d:"65",ans:"A",diff:"Easy"},
  {q:"In 30-60-90 triangle if shortest side is 5 hypotenuse = ?",a:"10",b:"5*sqrt(3)",c:"5*sqrt(2)",d:"15",ans:"A",diff:"Easy"},
  {q:"In 45-45-90 triangle if leg = 7 hypotenuse = ?",a:"7*sqrt(2)",b:"14",c:"7",d:"7*sqrt(3)",ans:"A",diff:"Easy"},
  {q:"Altitude from vertex A to BC in equilateral triangle of side a?",a:"a*sqrt(3)/2",b:"a/2",c:"a*sqrt(2)/2",d:"a",ans:"A",diff:"Easy"},
  {q:"Which set of sides forms a valid triangle: 2 3 6 or 4 5 6?",a:"4 5 6",b:"2 3 6",c:"Both",d:"Neither",ans:"A",diff:"Easy"},
  {q:"Area of triangle with vertices (0,0)(4,0)(0,3)?",a:"6",b:"12",c:"7",d:"5",ans:"A",diff:"Medium"},
  {q:"In triangle ABC angle A=60 B=80. Exterior angle at C?",a:"140",b:"120",c:"60",d:"80",ans:"A",diff:"Medium"},
  {q:"Triangle with sides 13 14 15. Area by Heron's?",a:"84",b:"90",c:"78",d:"96",ans:"A",diff:"Medium"},
  {q:"Area of right triangle with hypotenuse 10 one leg 6?",a:"24",b:"30",c:"20",d:"48",ans:"A",diff:"Medium"},
  {q:"Median length formula: m_a^2 = (2b^2+2c^2-a^2)/4. For a=4 b=3 c=5 m_a=?",a:"sqrt(12.5)",b:"3",c:"4",d:"5",ans:"A",diff:"Medium"},
  {q:"If two sides of a triangle are 6 and 8 and included angle = 90 area = ?",a:"24",b:"48",c:"12",d:"36",ans:"A",diff:"Medium"},
  {q:"In equilateral triangle with side a centroid divides each median in 2:1. Centroid height from base?",a:"a/(2*sqrt(3))",b:"a*sqrt(3)/6",c:"Both same: a*sqrt(3)/6",d:"a/3",ans:"C",diff:"Medium"},
  {q:"Triangle inequality: the largest angle is opposite?",a:"Longest side",b:"Shortest side",c:"Middle side",d:"Equal sides",ans:"A",diff:"Medium"},
  {q:"Sine rule: a/sinA = b/sinB = c/sinC = ?",a:"2R",b:"R",c:"r",d:"s",ans:"A",diff:"Medium"},
  {q:"Cosine rule: a^2 = b^2+c^2-2bc*cosA. For b=3 c=4 A=60 a=?",a:"sqrt(13)",b:"5",c:"sqrt(7)",d:"4",ans:"A",diff:"Medium"},
  {q:"Area = (1/2)*a*b*sinC. For a=5 b=6 C=30 area=?",a:"7.5",b:"15",c:"30",d:"12.5",ans:"A",diff:"Medium"},
  {q:"In isosceles triangle ABC AB=AC=10 BC=12. Area?",a:"48",b:"60",c:"40",d:"36",ans:"A",diff:"Medium"},
  {q:"For equilateral triangle area = sqrt(3)/4 * a^2. For a=8?",a:"16*sqrt(3)",b:"24*sqrt(3)",c:"8*sqrt(3)",d:"32",ans:"A",diff:"Medium"},
  {q:"In triangle ABC if AB=5 BC=6 CA=7 find the largest angle.",a:"Opposite to BC=no, A is opposite BC so find angle A",b:"Angle A is opposite BC=6",c:"Angle B opposite CA=7 is largest",d:"Angle C opposite AB=5",ans:"C",diff:"Medium"},
  {q:"Area of scalene triangle with sides 5 6 7 (use Heron's formula)?",a:"6*sqrt(6)/2...",b:"~14.7",c:"15",d:"12",ans:"B",diff:"Medium"},
  {q:"If perimeter of equilateral triangle = 36 find area.",a:"36*sqrt(3)",b:"36",c:"18*sqrt(3)",d:"12*sqrt(3)",ans:"A",diff:"Hard"},
  {q:"Stewart's theorem: b^2*m + c^2*n - a(m*n+d^2) = 0. Used to find?",a:"Length of cevian",b:"Area",c:"Altitude",d:"Circumradius",ans:"A",diff:"Hard"},
  {q:"In triangle ABC with angle A = 120 and AB=AC=5 find BC.",a:"5*sqrt(3)",b:"10",c:"5",d:"5*sqrt(2)",ans:"A",diff:"Hard"},
  {q:"Altitude from A in triangle with sides a b c = 2*Area/a. For sides 5 12 13?",a:"12",b:"5",c:"10",d:"13",ans:"A",diff:"Hard"},
  {q:"Find angle B in triangle if a=7 b=8 c=9 using cosine rule.",a:"cos B = (49+81-64)/126 = 66/126...",b:"60 degrees",c:"55 degrees approx",d:"70 degrees",ans:"C",diff:"Hard"},
  {q:"In equilateral triangle with altitude h find area in terms of h.",a:"h^2/sqrt(3) = h^2*sqrt(3)/3",b:"h^2",c:"h^2/2",d:"2h^2/sqrt(3)",ans:"A",diff:"Hard"},
  {q:"For triangle with sides a b c: r = Area/s = sqrt(s(s-a)(s-b)(s-c))/s. For 3 4 5?",a:"1",b:"2",c:"1.5",d:"3",ans:"A",diff:"Hard"},
  {q:"In right triangle hypotenuse = c altitude to hypotenuse = h. Area using both methods: (1/2)*ab = (1/2)*c*h so ab/c = h. For a=3 b=4 c=5 h=?",a:"12/5",b:"2",c:"3",d:"4",ans:"A",diff:"Hard"},
  {q:"Ptolemy's theorem vs triangle: sum of two sides > third. Can all angles be obtuse?",a:"No at most one angle can be obtuse",b:"Yes",c:"Two can be obtuse",d:"Depends on triangle",ans:"A",diff:"Hard"},
  {q:"For right triangle: median to hypotenuse = half hypotenuse. If hypotenuse=26 median=?",a:"13",b:"12",c:"15",d:"10",ans:"A",diff:"Hard"},
  {q:"In an equilateral triangle all medians altitudes angle bisectors perpendicular bisectors coincide. How many distinct centres?",a:"1",b:"2",c:"3",d:"4",ans:"A",diff:"Hard"},
  {q:"Triangle with perimeter 12 and area maximum is?",a:"Equilateral with side 4",b:"Isosceles",c:"Right triangle",d:"Scalene",ans:"A",diff:"Advanced"},
  {q:"Sine of angle A in triangle: Area = (1/2)bc sinA. Find sinA for b=5 c=6 Area=12.",a:"4/5",b:"3/5",c:"12/15",d:"2/5",ans:"A",diff:"Advanced"},
  {q:"Circumradius R = a/(2sinA) = abc/(4K). For equilateral a=6?",a:"2*sqrt(3)",b:"3",c:"6/sqrt(3)",d:"3*sqrt(3)",ans:"A",diff:"Advanced"},
  {q:"Napier analogies relate angles and sides. Used in?",a:"Oblique triangle solution",b:"Right triangle only",c:"Equilateral triangles",d:"Trigonometric identities",ans:"A",diff:"Advanced"},
  {q:"For triangle with angle A B C sum = pi. cosA + cosB + cosC <= ?",a:"3/2",b:"2",c:"1",d:"3",ans:"A",diff:"Advanced"},
  {q:"Area of pedal triangle (formed by feet of altitudes) = 2*Area*cosA*cosB*cosC. For equilateral?",a:"Area/4",b:"Area/2",c:"Area",d:"2*Area",ans:"A",diff:"Advanced"},
  {q:"Fermat point minimizes sum of distances to vertices. For equilateral triangle it coincides with?",a:"Centroid",b:"Circumcenter",c:"Incenter",d:"All four centres",ans:"D",diff:"Advanced"},
  {q:"Area of triangle = (1/2)|x1(y2-y3)+x2(y3-y1)+x3(y1-y2)| for (1,1)(4,1)(1,5)?",a:"6",b:"12",c:"8",d:"10",ans:"A",diff:"Advanced"},
  {q:"In triangle ABC r1+r2+r3 - r = 4R where r1 r2 r3 are exradii. This is?",a:"Exradii relation",b:"Euler formula",c:"Inradius formula",d:"Circumradius relation",ans:"A",diff:"Advanced"},
  {q:"Prove altitude is shortest distance from vertex to opposite side using?",a:"Any other line from vertex to opposite side is longer",b:"Pythagoras",c:"Sine rule",d:"Cosine rule",ans:"A",diff:"Advanced"}
],
22: [
  {q:"Sum of angles of a quadrilateral?",a:"360 degrees",b:"180 degrees",c:"270 degrees",d:"540 degrees",ans:"A",diff:"Easy"},
  {q:"In a parallelogram opposite angles are?",a:"Equal",b:"Supplementary",c:"Complementary",d:"Different",ans:"A",diff:"Easy"},
  {q:"In a rectangle all angles are?",a:"90 degrees",b:"60 degrees",c:"45 degrees",d:"120 degrees",ans:"A",diff:"Easy"},
  {q:"Diagonals of a parallelogram?",a:"Bisect each other",b:"Are equal",c:"Are perpendicular",d:"Are parallel",ans:"A",diff:"Easy"},
  {q:"In a rhombus all sides are?",a:"Equal",b:"Perpendicular",c:"Parallel in pairs",d:"None of these",ans:"A",diff:"Easy"},
  {q:"Diagonals of a rectangle are?",a:"Equal and bisect each other",b:"Perpendicular",c:"Different lengths",d:"Not related",ans:"A",diff:"Easy"},
  {q:"In a square diagonals are?",a:"Equal perpendicular and bisect each other",b:"Only equal",c:"Only perpendicular",d:"Only bisect",ans:"A",diff:"Easy"},
  {q:"Area of parallelogram with base 8 and height 5?",a:"40",b:"20",c:"80",d:"13",ans:"A",diff:"Easy"},
  {q:"Area of rhombus with diagonals 6 and 8?",a:"24",b:"48",c:"12",d:"36",ans:"A",diff:"Easy"},
  {q:"Area of trapezium with parallel sides 10 6 and height 4?",a:"32",b:"16",c:"40",d:"24",ans:"A",diff:"Easy"},
  {q:"Perimeter of square with side 7?",a:"28",b:"14",c:"49",d:"21",ans:"A",diff:"Easy"},
  {q:"Area of square with diagonal 10?",a:"50",b:"100",c:"25",d:"70",ans:"A",diff:"Easy"},
  {q:"A kite has?",a:"Two pairs of adjacent equal sides",b:"All sides equal",c:"Opposite sides equal",d:"All angles equal",ans:"A",diff:"Easy"},
  {q:"In trapezium exactly one pair of sides is?",a:"Parallel",b:"Equal",c:"Perpendicular",d:"All sides equal",ans:"A",diff:"Easy"},
  {q:"Which quadrilateral has diagonals that bisect at right angles?",a:"Rhombus",b:"Rectangle",c:"Parallelogram",d:"Trapezium",ans:"A",diff:"Easy"},
  {q:"Area of quadrilateral with diagonal d and perpendiculars h1 h2 = ?",a:"(1/2)*d*(h1+h2)",b:"d*(h1+h2)",c:"(1/4)*d*(h1+h2)",d:"d*h1*h2",ans:"A",diff:"Medium"},
  {q:"In parallelogram ABCD angle A = 70. Angle B = ?",a:"110",b:"70",c:"90",d:"140",ans:"A",diff:"Medium"},
  {q:"In rhombus one diagonal = 12 other = 16. Side = ?",a:"10",b:"12",c:"14",d:"8",ans:"A",diff:"Medium"},
  {q:"Area of rectangle = 80. One side = 10. Perimeter = ?",a:"36",b:"40",c:"80",d:"20",ans:"A",diff:"Medium"},
  {q:"In isosceles trapezium non-parallel sides are?",a:"Equal",b:"Different",c:"Parallel",d:"Perpendicular",ans:"A",diff:"Medium"},
  {q:"Sum of all interior angles of hexagon?",a:"720",b:"360",c:"540",d:"900",ans:"A",diff:"Medium"},
  {q:"ABCD parallelogram. E midpoint of BC. AE and BD intersect at F. AF:FE=?",a:"2:1",b:"1:1",c:"3:1",d:"1:2",ans:"A",diff:"Medium"},
  {q:"Diagonal of square of side a = ?",a:"a*sqrt(2)",b:"a",c:"2a",d:"a/sqrt(2)",ans:"A",diff:"Medium"},
  {q:"Area of trapezium with parallel sides 12 8 and non-parallel sides 5 each. Height?",a:"4",b:"3",c:"5",d:"6",ans:"A",diff:"Medium"},
  {q:"A quadrilateral with one pair of parallel sides and one pair of equal non-parallel sides is?",a:"Isosceles trapezium",b:"Rhombus",c:"Parallelogram",d:"Kite",ans:"A",diff:"Medium"},
  {q:"In a cyclic quadrilateral ABCD AB=6 BC=8 CD=5 DA=7. Area by?",a:"Brahmagupta's formula sqrt((s-a)(s-b)(s-c)(s-d))",b:"Simple formula",c:"Heron's formula",d:"Diagonal method",ans:"A",diff:"Medium"},
  {q:"Diagonal of rectangle with sides 5 and 12?",a:"13",b:"10",c:"15",d:"17",ans:"A",diff:"Medium"},
  {q:"Perimeter of rhombus with diagonal 16 and 12?",a:"40",b:"56",c:"32",d:"48",ans:"A",diff:"Medium"},
  {q:"In parallelogram adjacent angles are?",a:"Supplementary",b:"Equal",c:"Complementary",d:"90 degrees",ans:"A",diff:"Medium"},
  {q:"Area of kite with diagonals 9 and 14?",a:"63",b:"126",c:"31.5",d:"45",ans:"A",diff:"Medium"},
  {q:"ABCD rectangle diagonal bisects at O. Angle AOB = 60. Length of diagonal if sides are 5 and 5*sqrt(3)?",a:"10",b:"5*sqrt(2)",c:"5*sqrt(3)",d:"15",ans:"A",diff:"Hard"},
  {q:"Prove: diagonal of parallelogram divides it into two congruent triangles by?",a:"SAS or ASA",b:"SSS",c:"RHS",d:"AA",ans:"A",diff:"Hard"},
  {q:"Area of quadrilateral with vertices (0,0)(4,0)(4,3)(0,3)?",a:"12",b:"6",c:"24",d:"8",ans:"A",diff:"Hard"},
  {q:"In rhombus ABCD diagonals are 6 and 8. Angle at one vertex?",a:"2*arctan(3/4) = approx 73.7 degrees",b:"60 degrees",c:"90 degrees",d:"45 degrees",ans:"A",diff:"Hard"},
  {q:"Brahmagupta's formula for cyclic quadrilateral with sides a b c d and s=(a+b+c+d)/2: Area = sqrt((s-a)(s-b)(s-c)(s-d)). For 3 4 5 6?",a:"sqrt(864)/2 = approx 14.7",b:"18",c:"12",d:"16",ans:"A",diff:"Hard"},
  {q:"In trapezium ABCD AB || CD AB=10 CD=6 angle A=90 AD=8. Area?",a:"64",b:"48",c:"80",d:"32",ans:"A",diff:"Hard"},
  {q:"Varignon's theorem: midpoints of sides of any quadrilateral form a?",a:"Parallelogram",b:"Rectangle",c:"Rhombus",d:"Square",ans:"A",diff:"Hard"},
  {q:"Sum of squares of diagonals of parallelogram = sum of squares of?",a:"All four sides",b:"Two sides only",c:"Diagonals doubled",d:"Sides and diagonals",ans:"A",diff:"Hard"},
  {q:"Area of irregular quadrilateral using diagonal method: d=10 h1=3 h2=5 Area=?",a:"40",b:"80",c:"30",d:"50",ans:"A",diff:"Hard"},
  {q:"In square ABCD side a. Midpoints E F G H of AB BC CD DA form a smaller square. Its area?",a:"a^2/2",b:"a^2/4",c:"a^2",d:"a^2*sqrt(2)",ans:"A",diff:"Hard"},
  {q:"Prove diagonals of rhombus are perpendicular bisectors of each other using?",a:"SSS congruence of 4 triangles",b:"AA similarity",c:"BPT",d:"Circle properties",ans:"A",diff:"Advanced"},
  {q:"Cyclic quadrilateral has maximum area when it is?",a:"A square (if all sides equal)",b:"A rectangle",c:"A rhombus",d:"An isosceles trapezium",ans:"A",diff:"Advanced"},
  {q:"Area of quadrilateral with vertices A(1,2) B(3,4) C(5,1) D(3,0) using shoelace formula?",a:"8",b:"10",c:"6",d:"12",ans:"A",diff:"Advanced"},
  {q:"General quadrilateral area using diagonals d1 d2 and angle theta between them: Area = (1/2)*d1*d2*sin(theta). For d1=10 d2=8 theta=30?",a:"20",b:"40",c:"10",d:"80",ans:"A",diff:"Advanced"},
  {q:"Newton-Gauss line connects midpoints of diagonals of a complete quadrilateral. This is a property of?",a:"Complete quadrilateral",b:"Cyclic quadrilateral",c:"Parallelogram",d:"Trapezium",ans:"A",diff:"Advanced"},
  {q:"A tangential quadrilateral has an inscribed circle. Condition: sum of opposite sides are?",a:"Equal",b:"Different",c:"In ratio 1:1",d:"Cannot be determined",ans:"A",diff:"Advanced"},
  {q:"For parallelogram: a^2+b^2+c^2+d^2 = p^2+q^2 (diagonals p q sides a b c d = a a b b). Formula is?",a:"2(a^2+b^2) = p^2+q^2",b:"a^2+b^2 = p^2+q^2",c:"4(a^2+b^2) = p^2+q^2",d:"(a+b)^2 = p+q",ans:"A",diff:"Advanced"},
  {q:"Orthodiagonal quadrilateral: diagonals perpendicular. Area = (1/2)*d1*d2 applies to?",a:"Rhombus and kite",b:"All quadrilaterals",c:"Only squares",d:"Only rhombus",ans:"A",diff:"Advanced"},
  {q:"For cyclic quadrilateral maximum area is achieved when it is?",a:"A square (for equal sides)",b:"Rectangle",c:"Trapezium",d:"Rhombus",ans:"A",diff:"Advanced"},
  {q:"Shoelace formula for polygon with n vertices gives?",a:"Area",b:"Perimeter",c:"Number of diagonals",d:"Circumradius",ans:"A",diff:"Advanced"}
],
23: [
  {q:"A regular polygon has all sides and all angles?",a:"Equal",b:"Different",c:"Right angles only",d:"Supplementary",ans:"A",diff:"Easy"},
  {q:"Each interior angle of a regular hexagon?",a:"120 degrees",b:"60 degrees",c:"90 degrees",d:"108 degrees",ans:"A",diff:"Easy"},
  {q:"Sum of exterior angles of any regular polygon?",a:"360 degrees",b:"180 degrees",c:"720 degrees",d:"Depends on polygon",ans:"A",diff:"Easy"},
  {q:"Each exterior angle of regular octagon?",a:"45 degrees",b:"60 degrees",c:"30 degrees",d:"90 degrees",ans:"A",diff:"Easy"},
  {q:"Interior angle of regular pentagon?",a:"108 degrees",b:"72 degrees",c:"120 degrees",d:"90 degrees",ans:"A",diff:"Easy"},
  {q:"Number of diagonals of a hexagon?",a:"9",b:"6",c:"12",d:"15",ans:"A",diff:"Easy"},
  {q:"Sum of interior angles of pentagon?",a:"540 degrees",b:"360 degrees",c:"720 degrees",d:"180 degrees",ans:"A",diff:"Easy"},
  {q:"A regular polygon with 4 sides is a?",a:"Square",b:"Rectangle",c:"Rhombus",d:"Trapezium",ans:"A",diff:"Easy"},
  {q:"How many sides does a polygon have if each exterior angle is 24 degrees?",a:"15",b:"12",c:"18",d:"20",ans:"A",diff:"Easy"},
  {q:"Interior angle of equilateral triangle = ?",a:"60 degrees",b:"90 degrees",c:"120 degrees",d:"45 degrees",ans:"A",diff:"Easy"},
  {q:"Interior angle of regular 12-gon?",a:"150 degrees",b:"120 degrees",c:"144 degrees",d:"160 degrees",ans:"A",diff:"Easy"},
  {q:"Number of diagonals of a pentagon?",a:"5",b:"4",c:"6",d:"7",ans:"A",diff:"Easy"},
  {q:"Sum of interior angles of hexagon?",a:"720 degrees",b:"360 degrees",c:"540 degrees",d:"900 degrees",ans:"A",diff:"Easy"},
  {q:"Regular polygon exterior angle = 30. How many sides?",a:"12",b:"8",c:"15",d:"10",ans:"A",diff:"Easy"},
  {q:"Interior angle formula for regular n-gon: (n-2)*180/n. For n=10?",a:"144",b:"150",c:"135",d:"140",ans:"A",diff:"Easy"},
  {q:"Area of regular hexagon with side a?",a:"3*sqrt(3)*a^2/2",b:"6*a^2",c:"sqrt(3)*a^2",d:"2*sqrt(3)*a^2",ans:"A",diff:"Medium"},
  {q:"Area of regular polygon with n sides and side length a = (n*a^2)/(4*tan(pi/n)). For square a=5?",a:"25",b:"50",c:"100",d:"20",ans:"A",diff:"Medium"},
  {q:"Interior angle of regular 18-gon?",a:"160 degrees",b:"150 degrees",c:"170 degrees",d:"144 degrees",ans:"A",diff:"Medium"},
  {q:"Sum of interior angles of a 15-gon?",a:"2340 degrees",b:"1980 degrees",c:"2520 degrees",d:"2160 degrees",ans:"A",diff:"Medium"},
  {q:"Number of diagonals of n-gon = n(n-3)/2. For n=10?",a:"35",b:"40",c:"25",d:"45",ans:"A",diff:"Medium"},
  {q:"Circumradius of regular n-gon with side a = a/(2*sin(pi/n)). For equilateral triangle a=6?",a:"2*sqrt(3)",b:"3",c:"6/sqrt(3)",d:"sqrt(3)",ans:"A",diff:"Medium"},
  {q:"Inradius of regular n-gon: r = a/(2*tan(pi/n)). For square a=4?",a:"2",b:"4",c:"1",d:"2*sqrt(2)",ans:"A",diff:"Medium"},
  {q:"Regular hexagon can be divided into how many equilateral triangles?",a:"6",b:"4",c:"8",d:"3",ans:"A",diff:"Medium"},
  {q:"If each interior angle of polygon = 135 how many sides?",a:"8",b:"6",c:"10",d:"12",ans:"A",diff:"Medium"},
  {q:"Area of regular hexagon with side 4 cm?",a:"24*sqrt(3)",b:"48",c:"12*sqrt(3)",d:"16*sqrt(3)",ans:"A",diff:"Medium"},
  {q:"Pentagon has 5 diagonals. They form a smaller regular pentagon inside. This figure is?",a:"Pentagram star",b:"Hexagon",c:"Decagon",d:"Heptagon",ans:"A",diff:"Medium"},
  {q:"Interior angle increases as n increases. Approaches?",a:"180 degrees",b:"360 degrees",c:"90 degrees",d:"270 degrees",ans:"A",diff:"Medium"},
  {q:"For which polygon are the interior angles 90 degrees each?",a:"Square",b:"Rectangle",c:"Regular polygon with 90 degree angles only square",d:"Any rectangle",ans:"A",diff:"Medium"},
  {q:"A star polygon {5/2} is formed by connecting every 2nd vertex of regular pentagon. Points = ?",a:"5",b:"10",c:"6",d:"3",ans:"A",diff:"Medium"},
  {q:"Regular polygon with interior angle 162. Number of sides?",a:"20",b:"18",c:"24",d:"15",ans:"A",diff:"Medium"},
  {q:"Perimeter of regular hexagon with side 7?",a:"42",b:"35",c:"49",d:"56",ans:"A",diff:"Hard"},
  {q:"Regular octagon area with side a = 2(1+sqrt(2))a^2. For a=3?",a:"18+18*sqrt(2)... = 18(1+sqrt(2))",b:"18*sqrt(2)",c:"36",d:"18",ans:"A",diff:"Hard"},
  {q:"Each interior angle of regular polygon = 5 times exterior angle. Find n.",a:"12",b:"10",c:"15",d:"8",ans:"A",diff:"Hard"},
  {q:"Sum of all interior angles of dodecagon?",a:"1800 degrees",b:"1440 degrees",c:"2160 degrees",d:"1980 degrees",ans:"A",diff:"Hard"},
  {q:"Regular polygon inscribed in circle radius R. Side a = 2R*sin(pi/n). For hexagon R=5?",a:"5",b:"10",c:"5*sqrt(3)",d:"5*sqrt(2)",ans:"A",diff:"Hard"},
  {q:"Area of regular hexagon inscribed in circle radius R?",a:"3*sqrt(3)*R^2/2",b:"3R^2",c:"sqrt(3)*R^2",d:"2*sqrt(3)*R^2",ans:"A",diff:"Hard"},
  {q:"For n=3 4 5 6 the interior angles are 60 90 108 120. Difference between consecutive?",a:"30 18 12 (decreasing)",b:"All equal",c:"30 always",d:"Increasing",ans:"A",diff:"Hard"},
  {q:"A regular polygon has interior angle exceeding exterior angle by 108 degrees. Find n.",a:"10",b:"8",c:"12",d:"15",ans:"A",diff:"Hard"},
  {q:"If sum of interior angles = 2520 degrees find n.",a:"16",b:"14",c:"18",d:"12",ans:"A",diff:"Hard"},
  {q:"For regular polygon: ratio of perimeter to apothem = 2n*tan(pi/n). As n->inf this ratio -> ?",a:"2*pi",b:"pi",c:"4",d:"2",ans:"A",diff:"Hard"},
  {q:"Regular polygon inscribed in circle. As n->inf shape approaches?",a:"Circle",b:"Ellipse",c:"Square",d:"Hexagon",ans:"A",diff:"Advanced"},
  {q:"Area of polygon inscribed in circle radius R: A=n*R^2*sin(2pi/n)/2. For n->inf A -> ?",a:"pi*R^2",b:"2*pi*R^2",c:"pi*R^2/2",d:"4*R^2",ans:"A",diff:"Advanced"},
  {q:"Regular polygon exterior angle formula: 360/n. If two polygons have 6 and 12 sides their exterior angle ratio?",a:"2:1",b:"1:2",c:"1:1",d:"3:2",ans:"A",diff:"Advanced"},
  {q:"Golden ratio phi appears in regular?",a:"Pentagon",b:"Hexagon",c:"Square",d:"Octagon",ans:"A",diff:"Advanced"},
  {q:"Number of triangles formed by diagonals of regular hexagon from all vertices?",a:"20",b:"18",c:"24",d:"12",ans:"A",diff:"Advanced"},
  {q:"A tessellation is possible with regular polygons of?",a:"3 4 6 sides only",b:"All polygons",c:"5 and 8 only",d:"Any even-sided",ans:"A",diff:"Advanced"},
  {q:"Euler characteristic V-E+F=2 for convex polyhedron. For dodecahedron: F=12 V=20 E=?",a:"30",b:"24",c:"36",d:"20",ans:"A",diff:"Advanced"},
  {q:"Kepler-Poinsot polygons: self-intersecting regular polygons include?",a:"Pentagram",b:"Hexagram",c:"Both",d:"Neither",ans:"C",diff:"Advanced"},
  {q:"Interior angle of regular 360-gon?",a:"179 degrees",b:"178 degrees",c:"180 degrees",d:"Approaches 180",ans:"D",diff:"Advanced"},
  {q:"Regular polygon with n sides has n lines of symmetry and rotational symmetry of order?",a:"n",b:"2n",c:"n-1",d:"n/2",ans:"A",diff:"Advanced"}
],
24: [
  {q:"A right prism has lateral faces that are?",a:"Rectangles",b:"Triangles",c:"Parallelograms",d:"Trapezoids",ans:"A",diff:"Easy"},
  {q:"Volume of rectangular prism L=5 W=4 H=3?",a:"60",b:"20",c:"40",d:"120",ans:"A",diff:"Easy"},
  {q:"Total surface area of cube with side 4?",a:"96",b:"64",c:"48",d:"24",ans:"A",diff:"Easy"},
  {q:"Volume of cube with side 3?",a:"27",b:"9",c:"18",d:"81",ans:"A",diff:"Easy"},
  {q:"Lateral surface area of right prism = perimeter of base * height. Base perimeter 20 height 6?",a:"120",b:"60",c:"240",d:"40",ans:"A",diff:"Easy"},
  {q:"Number of faces of a triangular prism?",a:"5",b:"4",c:"6",d:"7",ans:"A",diff:"Easy"},
  {q:"Right prism with square base side 5 and height 10. Volume?",a:"250",b:"500",c:"125",d:"200",ans:"A",diff:"Easy"},
  {q:"Number of edges of a triangular prism?",a:"9",b:"6",c:"12",d:"8",ans:"A",diff:"Easy"},
  {q:"Total surface area of right prism = LSA + 2*base area. Triangular base sides 3 4 5 height = 10?",a:"120+24=144",b:"120",c:"144",d:"168",ans:"C",diff:"Easy"},
  {q:"Volume of prism with base area 25 and height 8?",a:"200",b:"100",c:"50",d:"400",ans:"A",diff:"Easy"},
  {q:"Right prism with hexagonal base side 2 and height 5. Volume?",a:"30*sqrt(3)",b:"60",c:"12*sqrt(3)*5",d:"15*sqrt(3)",ans:"A",diff:"Easy"},
  {q:"Number of vertices of rectangular prism?",a:"8",b:"6",c:"4",d:"12",ans:"A",diff:"Easy"},
  {q:"Right prism with equilateral triangular base side 4 height 9. Volume?",a:"36*sqrt(3)",b:"72",c:"18*sqrt(3)",d:"54",ans:"A",diff:"Easy"},
  {q:"Lateral surface area of cube with side a?",a:"4a^2",b:"6a^2",c:"a^2",d:"2a^2",ans:"A",diff:"Easy"},
  {q:"Cross-section of right prism parallel to base is?",a:"Congruent to base",b:"Smaller than base",c:"Different shape",d:"A triangle",ans:"A",diff:"Easy"},
  {q:"Right prism base is regular hexagon side 3 height 7. Volume?",a:"63*sqrt(3)/2*6... = 189*sqrt(3)/2",b:"63*sqrt(3)",c:"63",d:"126*sqrt(3)",ans:"B",diff:"Medium"},
  {q:"Right prism with square base side 6 and height 12. Total SA?",a:"288+72=360",b:"432",c:"288",d:"324",ans:"A",diff:"Medium"},
  {q:"Right triangular prism base 3 4 5 height 10. Volume?",a:"60",b:"120",c:"30",d:"90",ans:"A",diff:"Medium"},
  {q:"Volume of right prism with base area 48 and height 5?",a:"240",b:"120",c:"96",d:"480",ans:"A",diff:"Medium"},
  {q:"A right prism of height h with n-gon base. Lateral faces = ?",a:"n rectangles",b:"n triangles",c:"2 polygons",d:"n+2 polygons",ans:"A",diff:"Medium"},
  {q:"Right rectangular prism: LSA = 2h(l+w). For l=5 w=3 h=8?",a:"128",b:"64",c:"96",d:"144",ans:"A",diff:"Medium"},
  {q:"Total SA of right prism with pentagonal base (area 40 perimeter 25) height 10?",a:"330",b:"250",c:"300",d:"280",ans:"A",diff:"Medium"},
  {q:"Volume of right prism if cross-section area A and length L: V=?",a:"A*L",b:"A+L",c:"A/L",d:"2A*L",ans:"A",diff:"Medium"},
  {q:"Right prism volume = base area * height. Double the height doubles?",a:"Volume",b:"Surface area",c:"Both",d:"Neither",ans:"A",diff:"Medium"},
  {q:"In a right prism all lateral edges are?",a:"Perpendicular to base",b:"Parallel to base",c:"Oblique to base",d:"Equal to base side",ans:"A",diff:"Medium"},
  {q:"Diagonal of rectangular prism l=3 w=4 h=12?",a:"13",b:"12",c:"15",d:"10",ans:"A",diff:"Medium"},
  {q:"Right prism with base equilateral triangle side a and height h. LSA = ?",a:"3ah",b:"ah",c:"6ah",d:"a^2h",ans:"A",diff:"Medium"},
  {q:"Right prism with rectangular base 6x8 and height 10. Volume?",a:"480",b:"240",c:"96",d:"600",ans:"A",diff:"Medium"},
  {q:"A warehouse is a right prism with floor 20x15 m and height 8 m. Volume?",a:"2400",b:"1200",c:"4800",d:"600",ans:"A",diff:"Medium"},
  {q:"Right prism with base perimeter 36 and slant height 15. Lateral SA?",a:"540",b:"270",c:"180",d:"720",ans:"A",diff:"Medium"},
  {q:"Prism volume = 360. Height = 12. Base area = ?",a:"30",b:"25",c:"48",d:"60",ans:"A",diff:"Hard"},
  {q:"Two right prisms same height. Bases similar with ratio 2:3. Volume ratio?",a:"4:9",b:"8:27",c:"2:3",d:"1:1",ans:"A",diff:"Hard"},
  {q:"Right prism has base area 100 and total SA = 700. Height?",a:"5",b:"7.5",c:"10",d:"4",ans:"A",diff:"Hard"},
  {q:"Diagonal of cube of side a?",a:"a*sqrt(3)",b:"a*sqrt(2)",c:"a",d:"2a",ans:"A",diff:"Hard"},
  {q:"Right prism: if base is doubled and height halved volume?",a:"Same",b:"Doubles",c:"Halves",d:"Quadruples",ans:"A",diff:"Hard"},
  {q:"Prism with regular hexagon base side 4 height 6. Total SA?",a:"144+48*sqrt(3)",b:"96+48*sqrt(3)",c:"48+144*sqrt(3)",d:"72*sqrt(3)+144",ans:"A",diff:"Hard"},
  {q:"Volume of right prism with cross-section 3-4-5 right triangle and length 20?",a:"600",b:"120",c:"300",d:"240",ans:"A",diff:"Hard"},
  {q:"Right prism with square base. If volume = 500 and height = 5 find perimeter of base.",a:"20",b:"25",c:"40",d:"10",ans:"A",diff:"Hard"},
  {q:"Right prism: if all dimensions multiplied by k volume multiplied by?",a:"k^3",b:"k^2",c:"k",d:"k^4",ans:"A",diff:"Hard"},
  {q:"Total SA of right prism with base rectangle 4x3 and height 10?",a:"164",b:"120",c:"164",d:"180",ans:"C",diff:"Hard"},
  {q:"Right prism with base pentagonal area 100 and total SA 1000. Height?",a:"16",b:"20",c:"25",d:"10",ans:"A",diff:"Hard"},
  {q:"Euler's formula for prism: V-E+F=2. Triangular prism: V=6 E=9 F=?",a:"5",b:"4",c:"6",d:"7",ans:"A",diff:"Advanced"},
  {q:"Volume of prism = area of cross-section * length. For oblique prism length replaced by?",a:"Perpendicular distance between bases",b:"Slant height",c:"Lateral edge",d:"Height from base to top vertex",ans:"A",diff:"Advanced"},
  {q:"Right prism with n-gon base. Number of vertices = 2n edges = 3n faces = n+2. For n=6?",a:"12 18 8",b:"6 9 5",c:"12 18 6",d:"6 12 8",ans:"A",diff:"Advanced"},
  {q:"Cavalieri's principle: if two solids have equal cross-sections at every height they have equal?",a:"Volume",b:"Surface area",c:"Both",d:"Neither",ans:"A",diff:"Advanced"},
  {q:"A prism with square cross-section 4x4 and length 10. Volume?",a:"160",b:"80",c:"100",d:"200",ans:"A",diff:"Advanced"},
  {q:"Right prism total SA includes? How many faces?",a:"n lateral + 2 base faces",b:"n lateral only",c:"2 base only",d:"n+2 base",ans:"A",diff:"Advanced"},
  {q:"Right prism height h base regular n-gon side a. Ratio of volume to LSA?",a:"a*h*n/(4*tan(pi/n)) / (n*a*h) = 1/(4*tan(pi/n))*a",b:"h/a",c:"n*a",d:"Depends on n only",ans:"A",diff:"Advanced"},
  {q:"A right prism with equilateral triangular base. If volume = 270*sqrt(3) and height = 10 find side.",a:"6",b:"9",c:"12",d:"3",ans:"B",diff:"Advanced"},
  {q:"If a prism is cut by a plane parallel to base both parts are?",a:"Right prisms with same base",b:"Pyramids",c:"Cones",d:"Different shapes",ans:"A",diff:"Advanced"},
  {q:"Right prism with base area A and height h. Total surface area formula?",a:"2A + p*h (p=perimeter of base)",b:"A + p*h",c:"2A + 2p*h",d:"A*h",ans:"A",diff:"Advanced"}
],
25: [
  {q:"Volume of cone with radius 3 and height 4?",a:"12*pi",b:"36*pi",c:"9*pi",d:"48*pi",ans:"A",diff:"Easy"},
  {q:"Curved surface area of cone with radius r and slant height l?",a:"pi*r*l",b:"pi*r^2",c:"2*pi*r*l",d:"pi*r*(r+l)",ans:"A",diff:"Easy"},
  {q:"Total surface area of cone radius 5 slant height 13?",a:"90*pi",b:"65*pi",c:"130*pi",d:"25*pi",ans:"A",diff:"Easy"},
  {q:"Slant height of cone with radius 6 and height 8?",a:"10",b:"12",c:"8",d:"14",ans:"A",diff:"Easy"},
  {q:"Volume of cone = (1/3)*pi*r^2*h. Cone radius 7 height 12. Volume?",a:"196*pi",b:"588*pi",c:"196*pi",d:"49*pi*4",ans:"A",diff:"Easy"},
  {q:"Radius of base of cone = half slant height. If slant = 10 height = ?",a:"5*sqrt(3)",b:"5",c:"8",d:"6",ans:"A",diff:"Easy"},
  {q:"CSA of cone radius 6 slant height 10?",a:"60*pi",b:"36*pi",c:"100*pi",d:"120*pi",ans:"A",diff:"Easy"},
  {q:"If height of cone = radius find slant height in terms of radius r.",a:"r*sqrt(2)",b:"r",c:"2r",d:"r/sqrt(2)",ans:"A",diff:"Easy"},
  {q:"Volume of cone doubled if radius doubled with same height. By what factor?",a:"4",b:"2",c:"8",d:"3",ans:"A",diff:"Easy"},
  {q:"Total SA of cone = pi*r*(r+l). For r=3 l=5?",a:"24*pi",b:"15*pi",c:"9*pi",d:"45*pi",ans:"A",diff:"Easy"},
  {q:"Half-angle of cone at apex when radius = height?",a:"45 degrees",b:"30 degrees",c:"60 degrees",d:"90 degrees",ans:"A",diff:"Easy"},
  {q:"Cone with base radius 10 and height 24. Slant height?",a:"26",b:"20",c:"25",d:"28",ans:"A",diff:"Easy"},
  {q:"Volume cone A : volume cone B if same height but radius A = 2 * radius B?",a:"4:1",b:"2:1",c:"8:1",d:"1:4",ans:"A",diff:"Easy"},
  {q:"CSA of cone with diameter 14 and slant 25?",a:"175*pi",b:"350*pi",c:"49*pi",d:"245*pi",ans:"A",diff:"Easy"},
  {q:"Volume of cone in terms of its base area A and height h?",a:"Ah/3",b:"Ah",c:"2Ah/3",d:"Ah/2",ans:"A",diff:"Easy"},
  {q:"A right circular cone has radius 5 height 12 slant 13. Find total SA.",a:"90*pi",b:"65*pi",c:"25*pi",d:"130*pi",ans:"A",diff:"Medium"},
  {q:"Ratio of volume of cone to cylinder same radius and height?",a:"1:3",b:"1:2",c:"2:3",d:"1:1",ans:"A",diff:"Medium"},
  {q:"Cone with CSA 156*pi and slant height 13. Radius?",a:"12",b:"6",c:"8",d:"10",ans:"A",diff:"Medium"},
  {q:"Cone with radius 9 and height 12. Volume?",a:"324*pi",b:"972*pi",c:"108*pi",d:"243*pi",ans:"A",diff:"Medium"},
  {q:"Cone total SA = 96*pi and radius = 6. Slant height?",a:"10",b:"8",c:"12",d:"6",ans:"A",diff:"Medium"},
  {q:"A frustum of cone has radii R r and slant height l. CSA = pi*l*(R+r). Volume = pi*h*(R^2+Rr+r^2)/3. CSA for R=8 r=5 l=10?",a:"130*pi",b:"80*pi",c:"50*pi",d:"260*pi",ans:"A",diff:"Medium"},
  {q:"Cone volume 308*pi height 12. Radius?",a:"sqrt(77)... = (308*3/12) = 77 r=sqrt(77)?",b:"7",c:"11",d:"8",ans:"C",diff:"Medium"},
  {q:"If cone radius halved volume becomes?",a:"1/4 of original",b:"1/2",c:"1/8",d:"1/3",ans:"A",diff:"Medium"},
  {q:"Cone with apex angle 60 degrees. Half-angle = 30. Radius:height = ?",a:"tan30 = 1/sqrt(3) so r = h/sqrt(3)",b:"1:1",c:"sqrt(3):1",d:"1:2",ans:"A",diff:"Medium"},
  {q:"Cone slant height l radius r. If l = 2r find height in terms of r.",a:"r*sqrt(3)",b:"r",c:"2r",d:"r/sqrt(3)",ans:"A",diff:"Medium"},
  {q:"Two cones same base radius. Heights 3 and 7. Volume ratio?",a:"3:7",b:"7:3",c:"9:49",d:"1:1",ans:"A",diff:"Medium"},
  {q:"Total SA of cone radius 4 slant 9?",a:"52*pi",b:"36*pi",c:"16*pi",d:"64*pi",ans:"A",diff:"Medium"},
  {q:"Cone volume 1540/3 * pi height 7 find radius.",a:"sqrt(220/pi)...=?",b:"10",c:"7",d:"5",ans:"B",diff:"Medium"},
  {q:"Cone with same volume as cylinder. Cylinder r=5 h=6. Cone height if r same?",a:"18",b:"12",c:"6",d:"9",ans:"A",diff:"Medium"},
  {q:"Cone unrolled gives a sector with radius = slant height. Arc length = base circumference. Sector angle = ?",a:"2*pi*r/l (in radians) = 360*r/l degrees",b:"180 degrees",c:"90 degrees",d:"360 degrees",ans:"A",diff:"Medium"},
  {q:"Volume of cone radius 6 height 8 = ?",a:"96*pi",b:"288*pi",c:"48*pi",d:"192*pi",ans:"A",diff:"Hard"},
  {q:"A cone inscribed in cylinder same base and height. Volume of cone:cylinder = ?",a:"1:3",b:"1:2",c:"2:3",d:"1:4",ans:"A",diff:"Hard"},
  {q:"Frustum radii 4 and 2 height 6. Volume = (pi*6*(16+8+4))/3 = ?",a:"56*pi",b:"28*pi",c:"84*pi",d:"42*pi",ans:"A",diff:"Hard"},
  {q:"Cone CSA = pi*r*l. If r doubled and l halved new CSA = ?",a:"Same",b:"Double",c:"Half",d:"Quadruple",ans:"A",diff:"Hard"},
  {q:"Largest cone inscribed in sphere of radius R. Cone radius r height h = R+sqrt(R^2-r^2). Maximum volume when r^2 = 2R^2/3?",a:"8*pi*R^3/(3*sqrt(3))/3",b:"4*pi*R^3/3",c:"2*pi*R^3/3",d:"pi*R^3",ans:"A",diff:"Hard"},
  {q:"A solid right cone radius 7 height 24. If slant height forms angle with axis?",a:"arctan(7/24)=16.26 degrees approximately",b:"30 degrees",c:"45 degrees",d:"60 degrees",ans:"A",diff:"Hard"},
  {q:"Cone TSA = 4*CSA find relationship between r and l.",a:"r=3l/4",b:"r=l/3",c:"r=l/2",d:"r=2l/3",ans:"A",diff:"Hard"},
  {q:"A sector with angle 120 and radius 15 is rolled into a cone. Cone radius = ?",a:"5",b:"10",c:"15/2",d:"15",ans:"A",diff:"Hard"},
  {q:"Two cones have same slant height. Radii ratio 3:4. CSA ratio?",a:"3:4",b:"9:16",c:"27:64",d:"1:1",ans:"A",diff:"Hard"},
  {q:"Cone volume formula: (1/3)*pi*r^2*h. Derive it from integration concept?",a:"Sum of infinitely thin circular discs",b:"Empirical observation",c:"Cavalieri principle",d:"Both a and c",ans:"D",diff:"Hard"},
  {q:"Cone with apex at origin axis along z. Equation: x^2+y^2 = (r/h)^2 * z^2. This represents?",a:"Double cone",b:"Single cone",c:"Paraboloid",d:"Sphere",ans:"A",diff:"Advanced"},
  {q:"Frustum volume = pi*h*(R^2+Rr+r^2)/3. For R=6 r=3 h=7?",a:"147*pi",b:"441*pi/3",c:"Both equal",d:"189*pi",ans:"C",diff:"Advanced"},
  {q:"Lateral surface of cone unrolled is a sector. Arc/circumference = angle/360. So angle = 360*r/l. For r=5 l=13?",a:"138.46 degrees",b:"180 degrees",c:"120 degrees",d:"90 degrees",ans:"A",diff:"Advanced"},
  {q:"Maximum volume cone inscribed in sphere radius R: volume = 8*pi*R^3*(sqrt(3)/3)^3/3 ... actually at h=4R/3?",a:"32*pi*R^3/81",b:"4*pi*R^3/3",c:"pi*R^3",d:"2*pi*R^3/3",ans:"A",diff:"Advanced"},
  {q:"Cone with semicircular cross section perpendicular to axis. What is the cross-section shape?",a:"Semicircle",b:"Ellipse",c:"Triangle",d:"Parabola",ans:"C",diff:"Advanced"},
  {q:"Centroid of cone from base = h/4. For cone height 12 centroid is at?",a:"3",b:"4",c:"6",d:"2",ans:"A",diff:"Advanced"},
  {q:"Nappe: two nappes of a double cone meet at?",a:"Apex",b:"Base",c:"Centroid",d:"Midpoint",ans:"A",diff:"Advanced"},
  {q:"Solid angle subtended by cone at apex with half-angle theta = 2*pi*(1-cos(theta)). For theta=30?",a:"2*pi*(1-sqrt(3)/2)",b:"pi/6",c:"pi/3",d:"pi",ans:"A",diff:"Advanced"},
  {q:"A cone cut parallel to base 1/3 from apex. Volume of small cone : large cone?",a:"1:27",b:"1:9",c:"1:3",d:"1:8",ans:"A",diff:"Advanced"},
  {q:"Slant height l radius r height h: l^2=r^2+h^2. For l=25 r=7 h=?",a:"24",b:"20",c:"18",d:"15",ans:"A",diff:"Advanced"}
],
