15: [
  {q:"SI on Rs.1000 at 5% for 2 years?",a:"Rs.100",b:"Rs.50",c:"Rs.200",d:"Rs.150",ans:"A",diff:"Easy"},
  {q:"CI on Rs.1000 at 10% for 2 years?",a:"Rs.210",b:"Rs.200",c:"Rs.220",d:"Rs.100",ans:"A",diff:"Easy"},
  {q:"P=Rs.500 R=8% T=3 years SI=?",a:"Rs.120",b:"Rs.100",c:"Rs.150",d:"Rs.80",ans:"A",diff:"Easy"},
  {q:"SI = Rs.400 P=Rs.2000 T=2 years. Rate?",a:"10%",b:"8%",c:"12%",d:"5%",ans:"A",diff:"Easy"},
  {q:"At what rate SI on Rs.600 for 3 years = Rs.90?",a:"5%",b:"4%",c:"6%",d:"3%",ans:"A",diff:"Easy"},
  {q:"P=Rs.1500 R=6% SI=Rs.270. T=?",a:"3 years",b:"2 years",c:"4 years",d:"5 years",ans:"A",diff:"Easy"},
  {q:"CI formula: A = P(1+R/100)^T. P=1000 R=10% T=1 year A=?",a:"Rs.1100",b:"Rs.1010",c:"Rs.1050",d:"Rs.1200",ans:"A",diff:"Easy"},
  {q:"Difference between CI and SI for 2 years = P*(R/100)^2. For P=1000 R=10%?",a:"Rs.10",b:"Rs.20",c:"Rs.100",d:"Rs.5",ans:"A",diff:"Easy"},
  {q:"Principal doubles in 5 years at SI. Rate?",a:"20%",b:"10%",c:"25%",d:"15%",ans:"A",diff:"Easy"},
  {q:"On Rs.2000 at 5% for 3 years SI=?",a:"Rs.300",b:"Rs.200",c:"Rs.400",d:"Rs.150",ans:"A",diff:"Easy"},
  {q:"Amount = P + SI. P=500 SI=125 Amount=?",a:"Rs.625",b:"Rs.600",c:"Rs.650",d:"Rs.575",ans:"A",diff:"Easy"},
  {q:"CI on Rs.5000 at 8% for 1 year compounded annually?",a:"Rs.400",b:"Rs.450",c:"Rs.500",d:"Rs.350",ans:"A",diff:"Easy"},
  {q:"SI on Rs.800 at 5% for 2.5 years?",a:"Rs.100",b:"Rs.80",c:"Rs.120",d:"Rs.60",ans:"A",diff:"Easy"},
  {q:"At 10% per annum SI a sum becomes Rs.1300 in 3 years. Principal?",a:"Rs.1000",b:"Rs.1100",c:"Rs.900",d:"Rs.800",ans:"A",diff:"Easy"},
  {q:"In how many years will Rs.600 become Rs.900 at 10% SI?",a:"5 years",b:"3 years",c:"4 years",d:"6 years",ans:"A",diff:"Easy"},
  {q:"CI on Rs.10000 at 10% for 2 years compounded annually?",a:"Rs.2100",b:"Rs.2000",c:"Rs.1900",d:"Rs.2200",ans:"A",diff:"Medium"},
  {q:"Difference CI and SI for P=Rs.5000 R=8% T=2 years?",a:"Rs.32",b:"Rs.40",c:"Rs.25",d:"Rs.20",ans:"A",diff:"Medium"},
  {q:"Rs.2000 invested at 5% CI compounded annually. Amount after 3 years?",a:"Rs.2315.25",b:"Rs.2300",c:"Rs.2325",d:"Rs.2250",ans:"A",diff:"Medium"},
  {q:"SI on sum for 3 years at 6% = Rs.270. Sum?",a:"Rs.1500",b:"Rs.1200",c:"Rs.1800",d:"Rs.1000",ans:"A",diff:"Medium"},
  {q:"At what rate CI on Rs.1600 for 1.5 years compounded half-yearly = Rs.252.20?",a:"10%",b:"8%",c:"12%",d:"6%",ans:"A",diff:"Medium"},
  {q:"If SI for 3 years = Rs.600 and CI for 3 years > SI by Rs.25.50. Rate?",a:"5%",b:"6%",c:"4%",d:"8%",ans:"A",diff:"Medium"},
  {q:"A sum doubles in 8 years at SI. When will it triple?",a:"16 years",b:"12 years",c:"24 years",d:"20 years",ans:"A",diff:"Medium"},
  {q:"Compound interest compounded quarterly on Rs.8000 at 20% for 1 year?",a:"Rs.1724.05",b:"Rs.1600",c:"Rs.1800",d:"Rs.2000",ans:"A",diff:"Medium"},
  {q:"Present value of Rs.1331 at 10% CI for 3 years?",a:"Rs.1000",b:"Rs.900",c:"Rs.1100",d:"Rs.1200",ans:"A",diff:"Medium"},
  {q:"Two sums in ratio 4:5 invested at 6% and 5% SI for 2 years. Equal returns. Ratio check?",a:"4*6=24 vs 5*5=25 not equal so given is approximate",b:"Equal",c:"Cannot determine",d:"4:5",ans:"A",diff:"Medium"},
  {q:"A borrowed Rs.5000 at 5% for first year and 6% for second year SI. Total interest?",a:"Rs.550",b:"Rs.500",c:"Rs.600",d:"Rs.450",ans:"A",diff:"Medium"},
  {q:"CI on Rs.P at R% for 2 years = Rs.3P/25. Find R.",a:"20%",b:"25%",c:"10%",d:"15%",ans:"A",diff:"Medium"},
  {q:"Rs.1000 at 10% CI. After 3 years minus after 2 years = ?",a:"Rs.121",b:"Rs.110",c:"Rs.100",d:"Rs.131",ans:"A",diff:"Medium"},
  {q:"Effective annual rate for 10% compounded semi-annually?",a:"10.25%",b:"10%",c:"10.5%",d:"11%",ans:"A",diff:"Medium"},
  {q:"A person invests Rs.4000 at 12.5% SI. When will it become Rs.7000?",a:"6 years",b:"5 years",c:"8 years",d:"10 years",ans:"A",diff:"Medium"},
  {q:"CI on Rs.12000 at 10% for 3 years - SI for same = ?",a:"Rs.364",b:"Rs.400",c:"Rs.320",d:"Rs.372",ans:"A",diff:"Hard"},
  {q:"A sum at CI doubles in 4 years. In how many years will it become 8 times?",a:"12 years",b:"8 years",c:"16 years",d:"24 years",ans:"A",diff:"Hard"},
  {q:"Rs.6000 partly at 5% and rest at 8% SI. Total interest Rs.400 in 1 year. At 5%?",a:"Rs.2000",b:"Rs.4000",c:"Rs.3000",d:"Rs.1000",ans:"B",diff:"Hard"},
  {q:"CI for first year Rs.200 second year Rs.220. Rate and principal?",a:"10% Rs.2000",b:"10% Rs.1800",c:"11% Rs.2000",d:"10% Rs.2200",ans:"A",diff:"Hard"},
  {q:"Simple interest for 6 years at 5% = Rs.1200. Principal?",a:"Rs.4000",b:"Rs.3600",c:"Rs.5000",d:"Rs.2400",ans:"A",diff:"Hard"},
  {q:"At CI, what sum will produce Rs.X after n years at r% = X/(1+r/100)^n. For X=1331 n=3 r=10%?",a:"Rs.1000",b:"Rs.900",c:"Rs.1100",d:"Rs.1200",ans:"A",diff:"Hard"},
  {q:"Difference between CI annually and half-yearly on Rs.8000 at 10% for 1 year?",a:"Rs.20",b:"Rs.10",c:"Rs.40",d:"Rs.50",ans:"A",diff:"Hard"},
  {q:"A sum of money at SI triples in 15 years. Rate?",a:"13.33%",b:"15%",c:"10%",d:"20%",ans:"A",diff:"Hard"},
  {q:"If CI on Rs.P for 2 years is Rs.860 and SI for same is Rs.800, find R.",a:"15%",b:"12.5%",c:"10%",d:"20%",ans:"A",diff:"Hard"},
  {q:"Rs.10000 invested. Rs.4000 at 5% Rs.3000 at 6% Rs.3000 at 7% SI for 2 years. Total amount?",a:"Rs.11380",b:"Rs.11000",c:"Rs.11200",d:"Rs.11500",ans:"A",diff:"Hard"},
  {q:"Sum at CI at 20% for 3 years = Rs.17280. Sum?",a:"Rs.10000",b:"Rs.8000",c:"Rs.12000",d:"Rs.9000",ans:"A",diff:"Advanced"},
  {q:"Effective rate when nominal rate 12% compounded monthly?",a:"12.68%",b:"12%",c:"12.5%",d:"13%",ans:"A",diff:"Advanced"},
  {q:"P doubles at CI in n years. It becomes 4P in?",a:"2n years",b:"3n years",c:"4n years",d:"n^2 years",ans:"A",diff:"Advanced"},
  {q:"A sum invested at 10% CI for 2 years gives Rs.2310 more than 9% SI. Principal?",a:"Rs.100000",b:"Rs.50000",c:"Rs.200000",d:"Rs.80000",ans:"A",diff:"Advanced"},
  {q:"CI formula for fractional time T=n+f/12 months: A=P(1+R/100)^n*(1+fR/1200). For P=1000 R=10% T=2 years 6 months?",a:"Rs.1331*1.05=Rs.1397.55",b:"Rs.1300",c:"Rs.1350",d:"Rs.1400",ans:"A",diff:"Advanced"},
  {q:"Continuous compounding formula: A=Pe^(rt). For P=1000 r=10% t=1 year?",a:"Rs.1105.17",b:"Rs.1100",c:"Rs.1050",d:"Rs.1200",ans:"A",diff:"Advanced"},
  {q:"A debt of Rs.1000 to be paid in 2 equal installments. Rate 10% CI. Each installment?",a:"Rs.576.19",b:"Rs.500",c:"Rs.600",d:"Rs.550",ans:"A",diff:"Advanced"},
  {q:"A sum at 5% SI for 2 years = A. Same sum at 5% CI for 2 years = B. B - A = ?",a:"P*(0.05)^2 = 0.0025P",b:"0",c:"P*0.05",d:"P*0.1",ans:"A",diff:"Advanced"},
  {q:"Rs.10000 at 10% CI. After 10 years (use (1.1)^10 = 2.5937). Amount?",a:"Rs.25937",b:"Rs.20000",c:"Rs.30000",d:"Rs.22000",ans:"A",diff:"Advanced"},
  {q:"Rule of 72: years to double at rate r% = 72/r. At 6% double in?",a:"12 years",b:"6 years",c:"8 years",d:"9 years",ans:"A",diff:"Advanced"}
],
16: [
  {q:"Expand (a+b)^2.",a:"a^2+2ab+b^2",b:"a^2+b^2",c:"a^2-2ab+b^2",d:"a^2+ab+b^2",ans:"A",diff:"Easy"},
  {q:"Expand (a-b)^2.",a:"a^2-2ab+b^2",b:"a^2+2ab+b^2",c:"a^2-b^2",d:"a^2+b^2",ans:"A",diff:"Easy"},
  {q:"Expand (a+b)(a-b).",a:"a^2-b^2",b:"a^2+b^2",c:"a^2+2ab-b^2",d:"2a^2",ans:"A",diff:"Easy"},
  {q:"Expand (a+b)^3.",a:"a^3+3a^2b+3ab^2+b^3",b:"a^3+b^3",c:"a^3+3ab+b^3",d:"a^3-3a^2b+3ab^2-b^3",ans:"A",diff:"Easy"},
  {q:"Simplify sqrt(27).",a:"3*sqrt(3)",b:"9",c:"sqrt(9)*sqrt(3)",d:"3^(3/2)",ans:"A",diff:"Easy"},
  {q:"Simplify 2^(3/2).",a:"2*sqrt(2)",b:"sqrt(8)",c:"4",d:"2.83",ans:"A",diff:"Easy"},
  {q:"(a^2-b^2) = ?",a:"(a+b)(a-b)",b:"(a-b)^2",c:"(a+b)^2",d:"a^2+b^2",ans:"A",diff:"Easy"},
  {q:"Simplify 8^(2/3).",a:"4",b:"2",c:"16",d:"8",ans:"A",diff:"Easy"},
  {q:"Simplify (sqrt(3))^4.",a:"9",b:"3",c:"81",d:"27",ans:"A",diff:"Easy"},
  {q:"x^0 = ? for x ≠ 0",a:"1",b:"0",c:"x",d:"Undefined",ans:"A",diff:"Easy"},
  {q:"Simplify (a^3)(a^4).",a:"a^7",b:"a^12",c:"a^34",d:"a",ans:"A",diff:"Easy"},
  {q:"Simplify (a^3)/(a^2).",a:"a",b:"a^6",c:"a^5",d:"1",ans:"A",diff:"Easy"},
  {q:"(a*b)^n = ?",a:"a^n * b^n",b:"a^n + b^n",c:"(ab)^(2n)",d:"n^(ab)",ans:"A",diff:"Easy"},
  {q:"(a^m)^n = ?",a:"a^(mn)",b:"a^(m+n)",c:"a^(m-n)",d:"a^(m/n)",ans:"A",diff:"Easy"},
  {q:"Simplify a^(-2).",a:"1/a^2",b:"-a^2",c:"a^2",d:"-2a",ans:"A",diff:"Easy"},
  {q:"If a+b=5 and ab=6 find a^2+b^2.",a:"13",b:"19",c:"25",d:"11",ans:"A",diff:"Medium"},
  {q:"If a-b=3 and a^2-b^2=21 find a+b.",a:"7",b:"3",c:"5",d:"9",ans:"A",diff:"Medium"},
  {q:"Simplify (2^3 * 3^2) / (2^2 * 3^3).",a:"2/3",b:"3/2",c:"6",d:"1",ans:"A",diff:"Medium"},
  {q:"(x+1/x)=3 find x^2+1/x^2.",a:"7",b:"9",c:"5",d:"11",ans:"A",diff:"Medium"},
  {q:"Simplify (5^(1/2)) * (5^(3/2)).",a:"25",b:"5",c:"5*sqrt(5)",d:"125",ans:"A",diff:"Medium"},
  {q:"If x=sqrt(3)+1/sqrt(3) find x^2.",a:"4+2/3+... = 13/3",b:"4",c:"3+1/3",d:"5",ans:"A",diff:"Medium"},
  {q:"Simplify (8^(1/3))^2.",a:"4",b:"2",c:"8",d:"16",ans:"A",diff:"Medium"},
  {q:"a^3+b^3=(a+b)(a^2-ab+b^2). For a=2 b=1?",a:"9",b:"7",c:"10",d:"8",ans:"A",diff:"Medium"},
  {q:"a^3-b^3=(a-b)(a^2+ab+b^2). For a=3 b=1?",a:"26",b:"24",c:"28",d:"20",ans:"A",diff:"Medium"},
  {q:"Simplify: (x^2-y^2)/(x-y)?",a:"x+y",b:"x-y",c:"x*y",d:"1",ans:"A",diff:"Medium"},
  {q:"Rationalise 5/(sqrt(3)+sqrt(2))?",a:"5(sqrt(3)-sqrt(2))",b:"5/sqrt(5)",c:"5(sqrt(3)+sqrt(2))",d:"sqrt(3)-sqrt(2)",ans:"A",diff:"Medium"},
  {q:"Simplify 16^(3/4).",a:"8",b:"4",c:"16",d:"12",ans:"A",diff:"Medium"},
  {q:"If a+b+c=0 find a^3+b^3+c^3.",a:"3abc",b:"0",c:"abc",d:"a+b+c",ans:"A",diff:"Medium"},
  {q:"Simplify (a^(1/2)+b^(1/2))(a^(1/2)-b^(1/2)).",a:"a-b",b:"a+b",c:"sqrt(a-b)",d:"sqrt(ab)",ans:"A",diff:"Medium"},
  {q:"If x^(1/3) = 2 find x.",a:"8",b:"6",c:"4",d:"2",ans:"A",diff:"Medium"},
  {q:"If x+y=7 and xy=10 find x^3+y^3.",a:"133",b:"103",c:"163",d:"143",ans:"A",diff:"Hard"},
  {q:"Simplify (4^(n+1) - 4^n) / (2^(2n-1)).",a:"8",b:"4",c:"2",d:"16",ans:"A",diff:"Hard"},
  {q:"If sqrt(x)+1/sqrt(x)=2sqrt(3) find x+1/x.",a:"10",b:"11",c:"12",d:"9",ans:"A",diff:"Hard"},
  {q:"Simplify (a^2+b^2+c^2-ab-bc-ca) given a+b+c=0.",a:"a^2+b^2+c^2",b:"0",c:"abc",d:"(a+b+c)^2",ans:"A",diff:"Hard"},
  {q:"Rationalise 1/(sqrt(6)-sqrt(5)).",a:"sqrt(6)+sqrt(5)",b:"sqrt(6)-sqrt(5)",c:"1/(sqrt(6)+sqrt(5))",d:"sqrt(11)",ans:"A",diff:"Hard"},
  {q:"If a=3+2*sqrt(2) find a - 1/a.",a:"4*sqrt(2)",b:"2*sqrt(2)",c:"3*sqrt(2)",d:"sqrt(2)",ans:"A",diff:"Hard"},
  {q:"(x^a/x^b)^(a+b) * (x^b/x^c)^(b+c) * (x^c/x^a)^(c+a) = ?",a:"1",b:"x^abc",c:"0",d:"x",ans:"A",diff:"Hard"},
  {q:"Simplify (6+sqrt(35))*(6-sqrt(35)).",a:"1",b:"36-35=1",c:"-1",d:"71",ans:"A",diff:"Hard"},
  {q:"If 2x=3y=6^(-z) find 1/x+1/y+1/z.",a:"0",b:"1",c:"2",d:"-1",ans:"A",diff:"Hard"},
  {q:"Simplify (a+b+c)^2 - (a-b-c)^2.",a:"4a(b+c)",b:"4bc",c:"4ab+4ac",d:"2a(b+c)",ans:"A",diff:"Hard"},
  {q:"If p+q+r=1 and p^2+q^2+r^2=2 find pq+qr+rp.",a:"-1/2",b:"1/2",c:"-1",d:"1",ans:"A",diff:"Hard"},
  {q:"(sqrt(2)+1)^6 + (sqrt(2)-1)^6 = ?",a:"198",b:"100",c:"200",d:"198",ans:"A",diff:"Advanced"},
  {q:"If x^(1/2) + y^(1/2) = (x+y)^(1/2) then?",a:"x=0 or y=0",b:"x=y",c:"Always true",d:"Never true",ans:"A",diff:"Advanced"},
  {q:"Simplify sum: 1/(1+a^(b-c)) + 1/(1+a^(c-b)) = ?",a:"1",b:"2",c:"0",d:"a",ans:"A",diff:"Advanced"},
  {q:"Find value of (a^x/a^y)^(x+y) * (a^y/a^z)^(y+z) * (a^z/a^x)^(z+x).",a:"1",b:"a",c:"0",d:"a^(xyz)",ans:"A",diff:"Advanced"},
  {q:"If 2^a = 3^b = 6^(-c) then 1/a+1/b+1/c = ?",a:"0",b:"1",c:"1/6",d:"-1",ans:"A",diff:"Advanced"},
  {q:"Simplify (x^a)^(1/b) * (x^b)^(1/a).",a:"x^(a/b+b/a)",b:"x^2",c:"x^(a+b)",d:"x",ans:"A",diff:"Advanced"},
  {q:"(64)^(2/3) / (27)^(2/3) = ?",a:"16/9",b:"4/3",c:"256/729",d:"8/3",ans:"A",diff:"Advanced"},
  {q:"If a=5+2*sqrt(6) find sqrt(a) - 1/sqrt(a).",a:"2*sqrt(2)",b:"2*sqrt(3)",c:"2*sqrt(6)",d:"4",ans:"A",diff:"Advanced"},
  {q:"The expression (1+1/n)^n as n->inf approaches?",a:"e",b:"2",c:"3",d:"pi",ans:"A",diff:"Advanced"}
],
17: [
  {q:"Point of intersection of y=2x+1 and y=3?",a:"(1,3)",b:"(3,7)",c:"(0,3)",d:"(2,5)",ans:"A",diff:"Easy"},
  {q:"Slope of line y = 3x - 5?",a:"3",b:"-5",c:"5",d:"-3",ans:"A",diff:"Easy"},
  {q:"Y-intercept of y = 2x + 7?",a:"7",b:"2",c:"-7",d:"0",ans:"A",diff:"Easy"},
  {q:"Which quadrant is point (-3, 4) in?",a:"II",b:"I",c:"III",d:"IV",ans:"A",diff:"Easy"},
  {q:"Does (2, 5) lie on y = 2x + 1?",a:"Yes",b:"No",c:"Cannot determine",d:"On the axis",ans:"A",diff:"Easy"},
  {q:"Graph of y = 0 is the?",a:"x-axis",b:"y-axis",c:"Origin",d:"Line y=1",ans:"A",diff:"Easy"},
  {q:"Graph of x = 0 is the?",a:"y-axis",b:"x-axis",c:"Origin",d:"Line x=1",ans:"A",diff:"Easy"},
  {q:"Line x + y = 5 passes through?",a:"(2,3)",b:"(1,1)",c:"(3,3)",d:"(0,0)",ans:"A",diff:"Easy"},
  {q:"In y = mx + c, m represents?",a:"Slope",b:"Y-intercept",c:"X-intercept",d:"Constant",ans:"A",diff:"Easy"},
  {q:"Slope of a horizontal line?",a:"0",b:"1",c:"Undefined",d:"-1",ans:"A",diff:"Easy"},
  {q:"Slope of a vertical line?",a:"Undefined",b:"0",c:"1",d:"-1",ans:"A",diff:"Easy"},
  {q:"Two lines y=2x+1 and y=2x-3 are?",a:"Parallel",b:"Perpendicular",c:"Coincident",d:"Intersecting",ans:"A",diff:"Easy"},
  {q:"Where does y = x intersect y-axis?",a:"(0,0)",b:"(1,0)",c:"(0,1)",d:"(1,1)",ans:"A",diff:"Easy"},
  {q:"Slope of line through (0,0) and (3,6)?",a:"2",b:"3",c:"1/2",d:"6",ans:"A",diff:"Easy"},
  {q:"Line y = -x + 4 has slope?",a:"-1",b:"1",c:"4",d:"-4",ans:"A",diff:"Easy"},
  {q:"Solve graphically: x+y=5 and x-y=1. Solution?",a:"(3,2)",b:"(2,3)",c:"(1,4)",d:"(4,1)",ans:"A",diff:"Medium"},
  {q:"The lines 2x+3y=6 and 4x+6y=12 are?",a:"Coincident",b:"Parallel",c:"Intersecting",d:"Perpendicular",ans:"A",diff:"Medium"},
  {q:"For what value of k are lines kx+2y=3 and 3x+6y=9 parallel?",a:"1",b:"2",c:"3",d:"6",ans:"A",diff:"Medium"},
  {q:"Intersection of y=3x-1 and y=x+5?",a:"(3,8)",b:"(2,5)",c:"(4,11)",d:"(1,2)",ans:"A",diff:"Medium"},
  {q:"X-intercept of 2x + 3y = 12?",a:"6",b:"4",c:"3",d:"12",ans:"A",diff:"Medium"},
  {q:"Y-intercept of 5x - 4y = 20?",a:"-5",b:"5",c:"4",d:"-4",ans:"A",diff:"Medium"},
  {q:"Equation of line parallel to y=3x+2 through (1,5)?",a:"y=3x+2",b:"y=3x-2+5... no",c:"y=3x+2",d:"y=3x+5",ans:"A",diff:"Medium"},
  {q:"Equation of x-axis?",a:"y=0",b:"x=0",c:"y=x",d:"y=1",ans:"A",diff:"Medium"},
  {q:"Point of intersection of lines x=3 and y=4?",a:"(3,4)",b:"(4,3)",c:"(0,4)",d:"(3,0)",ans:"A",diff:"Medium"},
  {q:"Which system has no solution: x+y=3 and 2x+2y=5?",a:"This system",b:"x+y=3 and x-y=1",c:"x+y=4 and x-y=2",d:"None",ans:"A",diff:"Medium"},
  {q:"A line with positive slope going through origin is in which quadrants?",a:"I and III",b:"II and IV",c:"I and II",d:"I only",ans:"A",diff:"Medium"},
  {q:"Slope of line perpendicular to y=2x+1?",a:"-1/2",b:"2",c:"1/2",d:"-2",ans:"A",diff:"Medium"},
  {q:"Line through (1,2) and (3,8) has slope?",a:"3",b:"2",c:"4",d:"6",ans:"A",diff:"Medium"},
  {q:"Equation of line through origin with slope 5?",a:"y=5x",b:"y=5",c:"x=5",d:"y=x+5",ans:"A",diff:"Medium"},
  {q:"Two equations 3x+2y=12 and x+y=5. Solve for x.",a:"2",b:"3",c:"4",d:"1",ans:"A",diff:"Medium"},
  {q:"For lines a1x+b1y+c1=0 and a2x+b2y+c2=0 coincident if a1/a2=b1/b2=c1/c2?",a:"Yes",b:"No",c:"Only if c1=c2",d:"Only if a1=a2",ans:"A",diff:"Hard"},
  {q:"Graphical solution of 2x-y=4 and x+y=5?",a:"(3,2)",b:"(2,3)",c:"(1,4)",d:"(4,1)",ans:"A",diff:"Hard"},
  {q:"Line passes through A(1,2) and B(4,8). Point on line at x=7?",a:"(7,14)",b:"(7,12)",c:"(7,16)",d:"(7,10)",ans:"A",diff:"Hard"},
  {q:"Three lines x+y=6 x-y=2 and 2x+3y=14 form a triangle?",a:"Yes",b:"No concurrent",c:"Two are parallel",d:"Cannot determine",ans:"A",diff:"Hard"},
  {q:"Area of triangle formed by x+y=4 x=0 and y=0?",a:"8 sq units",b:"4 sq units",c:"16 sq units",d:"2 sq units",ans:"A",diff:"Hard"},
  {q:"Solve by graph: 2x+y=7 and x+2y=8. Sum x+y=?",a:"5",b:"3",c:"7",d:"15",ans:"A",diff:"Hard"},
  {q:"Equation of line equidistant from y=3 and y=7?",a:"y=5",b:"y=4",c:"y=6",d:"y=10",ans:"A",diff:"Hard"},
  {q:"Lines y=3x+1 and y=3x+7 intersect at?",a:"Never (parallel)",b:"(0,4)",c:"(1,1)",d:"y-axis",ans:"A",diff:"Hard"},
  {q:"Family of lines through (2,3): y-3=m(x-2). Which value of m gives y=2x-1?",a:"m=2",b:"m=1",c:"m=3",d:"m=-1",ans:"A",diff:"Hard"},
  {q:"Intercept form of line: x/a + y/b = 1. Line through (3,0) and (0,4). Equation?",a:"x/3+y/4=1",b:"4x+3y=12",c:"Both a and b",d:"x+y=7",ans:"C",diff:"Hard"},
  {q:"For what values of a is 2x+ay=4 and 3x+2y=6 consistent?",a:"All a except 4/3",b:"a=4/3",c:"a=0",d:"All values",ans:"A",diff:"Advanced"},
  {q:"Lines 3x-4y=5 and 4x+3y=10 are?",a:"Perpendicular",b:"Parallel",c:"Same line",d:"Coincident",ans:"A",diff:"Advanced"},
  {q:"Sum of intercepts of line (x/3)+(y/4)=1?",a:"7",b:"12",c:"1",d:"3/4",ans:"A",diff:"Advanced"},
  {q:"If a line bisects the first quadrant angle it has slope?",a:"1",b:"-1",c:"0",d:"Undefined",ans:"A",diff:"Advanced"},
  {q:"Equation of line with equal intercepts passing through (4,3)?",a:"x+y=7",b:"x=y",c:"x-y=1",d:"2x+y=11",ans:"A",diff:"Advanced"},
  {q:"Lines x+2y=3 and 2x+4y=5 are?",a:"Parallel (no solution)",b:"Same line",c:"Intersecting",d:"Perpendicular",ans:"A",diff:"Advanced"},
  {q:"A line segment from (2,5) to (6,1). Midpoint?",a:"(4,3)",b:"(3,4)",c:"(5,2)",d:"(2,6)",ans:"A",diff:"Advanced"},
  {q:"If 3 lines are concurrent they pass through?",a:"Same point",b:"Same line",c:"Different points",d:"Origin only",ans:"A",diff:"Advanced"},
  {q:"Solve: ax+by=a-b and bx-ay=a+b. x+y=?",a:"1",b:"0",c:"a+b",d:"a-b",ans:"A",diff:"Advanced"},
  {q:"Graphical method uniquely solves a 2-variable linear system when lines?",a:"Intersect at exactly one point",b:"Are parallel",c:"Coincide",d:"Have the same slope",ans:"A",diff:"Advanced"}
],
18: [
  {q:"The centroid of a triangle divides each median in ratio?",a:"2:1",b:"1:2",c:"1:1",d:"3:1",ans:"A",diff:"Easy"},
  {q:"The circumcenter is equidistant from?",a:"All three vertices",b:"All three sides",c:"Centroid",d:"Orthocenter",ans:"A",diff:"Easy"},
  {q:"The incenter is equidistant from?",a:"All three sides",b:"All three vertices",c:"Centroid",d:"Circumcenter",ans:"A",diff:"Easy"},
  {q:"The orthocenter is the intersection of?",a:"Altitudes",b:"Medians",c:"Angle bisectors",d:"Perpendicular bisectors",ans:"A",diff:"Easy"},
  {q:"The centroid is the intersection of?",a:"Medians",b:"Altitudes",c:"Angle bisectors",d:"Perpendicular bisectors",ans:"A",diff:"Easy"},
  {q:"In an equilateral triangle all four centres?",a:"Coincide",b:"Form a triangle",c:"Are at vertices",d:"Are outside triangle",ans:"A",diff:"Easy"},
  {q:"The circumcenter of a right triangle lies at?",a:"Midpoint of hypotenuse",b:"Inside the triangle",c:"Outside the triangle",d:"On a leg",ans:"A",diff:"Easy"},
  {q:"The orthocenter of an obtuse triangle lies?",a:"Outside the triangle",b:"Inside",c:"At vertex",d:"At midpoint of hypotenuse",ans:"A",diff:"Easy"},
  {q:"For an acute triangle the circumcenter lies?",a:"Inside",b:"Outside",c:"At a vertex",d:"On hypotenuse",ans:"A",diff:"Easy"},
  {q:"The incenter always lies?",a:"Inside the triangle",b:"Outside",c:"At vertex",d:"On circumcircle",ans:"A",diff:"Easy"},
  {q:"Euler line passes through which three centres?",a:"Centroid circumcenter orthocenter",b:"Incenter centroid circumcenter",c:"All four centres",d:"Incenter orthocenter centroid",ans:"A",diff:"Easy"},
  {q:"The median from a vertex goes to?",a:"Midpoint of opposite side",b:"Foot of altitude",c:"Incenter",d:"Centroid",ans:"A",diff:"Easy"},
  {q:"The perpendicular bisector of a side passes through?",a:"Circumcenter",b:"Incenter",c:"Centroid",d:"Orthocenter",ans:"A",diff:"Easy"},
  {q:"An altitude is perpendicular to?",a:"Opposite side",b:"Adjacent side",c:"Median",d:"Angle bisector",ans:"A",diff:"Easy"},
  {q:"The angle bisector from a vertex bisects?",a:"The angle at that vertex",b:"The opposite side equally",c:"The altitude",d:"The median",ans:"A",diff:"Easy"},
  {q:"Centroid coordinates of triangle with vertices (x1,y1)(x2,y2)(x3,y3)?",a:"((x1+x2+x3)/3,(y1+y2+y3)/3)",b:"Average of two vertices",c:"Midpoint of hypotenuse",d:"Cannot be determined",ans:"A",diff:"Medium"},
  {q:"Circumradius R of triangle with sides a b c and area K: R = abc/(4K). For equilateral side a?",a:"a/sqrt(3)",b:"a*sqrt(3)/2",c:"a/sqrt(3)",d:"2a/sqrt(3)",ans:"A",diff:"Medium"},
  {q:"Inradius r = Area/semi-perimeter. For equilateral triangle of side a?",a:"a/(2*sqrt(3))",b:"a*sqrt(3)/6",c:"Both equal",d:"a/sqrt(3)",ans:"C",diff:"Medium"},
  {q:"For right triangle with legs 3 4 and hypotenuse 5 where is circumcenter?",a:"Midpoint of hypotenuse (2.5 from each vertex)",b:"Inside",c:"At right angle vertex",d:"Outside",ans:"A",diff:"Medium"},
  {q:"Relation between Euler line elements: OG:GH = 1:2 where O=circumcenter G=centroid H=orthocenter?",a:"True",b:"False G is midpoint",c:"Ratio is 2:1",d:"Not on same line",ans:"A",diff:"Medium"},
  {q:"Centroid divides median in ratio 2:1 from vertex. If median length = 12 cm vertex-to-centroid =?",a:"8 cm",b:"6 cm",c:"4 cm",d:"9 cm",ans:"A",diff:"Medium"},
  {q:"The orthocenter of equilateral triangle ABC coincides with?",a:"All four centres",b:"Centroid only",c:"Circumcenter only",d:"Incenter only",ans:"A",diff:"Medium"},
  {q:"For isosceles triangle with AB=AC the centroid circumcenter incenter and orthocenter all lie on?",a:"Axis of symmetry",b:"Base BC",c:"Circumcircle",d:"Altitudes only",ans:"A",diff:"Medium"},
  {q:"If circumcenter is O and circumradius R, then OA=OB=OC=?",a:"R",b:"2R",c:"R/2",d:"R*sqrt(3)",ans:"A",diff:"Medium"},
  {q:"The incircle touches all three sides. Inradius of triangle with area 84 and perimeter 42?",a:"4",b:"6",c:"7",d:"3",ans:"A",diff:"Medium"},
  {q:"Excenters of a triangle are the centers of?",a:"Excircles (opposite to each vertex)",b:"Circumcircle",c:"Incircle",d:"Nine-point circles",ans:"A",diff:"Medium"},
  {q:"For a triangle with angles A B C orthocentre H and circumcentre O: angle BOC = ?",a:"2A",b:"A",c:"180-A",d:"90+A",ans:"A",diff:"Medium"},
  {q:"Nine-point circle passes through?",a:"Midpoints of sides feet of altitudes midpoints of vertex-to-orthocenter",b:"Only vertices",c:"Only midpoints",d:"All centres",ans:"A",diff:"Medium"},
  {q:"The centroid of a triangle with vertices (0,0)(6,0)(0,6) is?",a:"(2,2)",b:"(3,3)",c:"(1,1)",d:"(0,3)",ans:"A",diff:"Medium"},
  {q:"For acute triangle which is the order from innermost: incentre is inside all of them. Order of distances from vertices?",a:"Incenter closest to sides circumcenter farthest",b:"Circumcenter inside incenter outside",c:"Orthocenter always innermost",d:"Cannot compare",ans:"A",diff:"Medium"},
  {q:"Circumcenter of triangle (0,0)(4,0)(0,3)?",a:"(2,1.5)",b:"(1.33,1)",c:"(2,3)",d:"(0,0)",ans:"A",diff:"Hard"},
  {q:"Orthocenter of right triangle is at?",a:"The vertex of right angle",b:"Midpoint of hypotenuse",c:"Circumcenter",d:"Centroid",ans:"A",diff:"Hard"},
  {q:"For triangle with vertices A(1,2) B(3,4) C(5,0) find centroid.",a:"(3,2)",b:"(2,3)",c:"(3,1)",d:"(4,2)",ans:"A",diff:"Hard"},
  {q:"Show that distance between circumcenter O and centroid G: OG = R/3 * sqrt(9-a^2/R^2...)?",a:"OG^2 = R^2 - (abc)^2/(... complex formula)",b:"OG = R/3",c:"OG = 0 always",d:"OG = 2R",ans:"A",diff:"Hard"},
  {q:"In triangle ABC if H is orthocenter then AH = ?",a:"2R*cosA",b:"R*cosA",c:"2R*sinA",d:"R*sinA",ans:"A",diff:"Hard"},
  {q:"For equilateral triangle of side a circumradius R = ?",a:"a/sqrt(3)",b:"a*sqrt(3)/3",c:"Both equal",d:"a/2",ans:"C",diff:"Hard"},
  {q:"For equilateral triangle inradius r = ?",a:"a/(2*sqrt(3)) = a*sqrt(3)/6",b:"a/2",c:"a*sqrt(3)/4",d:"a/sqrt(3)",ans:"A",diff:"Hard"},
  {q:"The Euler line exists for?",a:"All non-equilateral triangles",b:"Only right triangles",c:"Only isosceles",d:"All triangles",ans:"A",diff:"Hard"},
  {q:"Angle subtended at circumcenter by chord BC = angle A * 2. This is?",a:"Inscribed angle theorem",b:"Euler line theorem",c:"Centroid theorem",d:"Altitude theorem",ans:"A",diff:"Hard"},
  {q:"Orthocentre of triangle (0,0)(2,0)(0,2)?",a:"(0,0)",b:"(1,1)",c:"(2,2)",d:"(0,2)",ans:"A",diff:"Hard"},
  {q:"For triangle with angle A=30 the arc BC (not containing A) of circumcircle subtends angle?",a:"60 degrees at center",b:"30 degrees",c:"90 degrees",d:"120 degrees",ans:"A",diff:"Advanced"},
  {q:"Nagel point is related to?",a:"Excircles",b:"Incircle",c:"Circumcircle",d:"Medians",ans:"A",diff:"Advanced"},
  {q:"The nine-point circle radius = ?",a:"R/2",b:"R",c:"2R",d:"R/3",ans:"A",diff:"Advanced"},
  {q:"Symmedian point is the intersection of?",a:"Symmedians",b:"Medians",c:"Altitudes",d:"Angle bisectors",ans:"A",diff:"Advanced"},
  {q:"For obtuse triangle where does orthocenter lie?",a:"Outside the triangle",b:"Inside",c:"On hypotenuse",d:"At obtuse vertex",ans:"A",diff:"Advanced"},
  {q:"Feuerbach's theorem: the incircle is internally tangent to?",a:"Nine-point circle",b:"Circumcircle",c:"Excircle",d:"Euler circle",ans:"A",diff:"Advanced"},
  {q:"Centroid divides distance from vertex to midpoint of opposite side. From midpoint to centroid?",a:"1/3 of median",b:"2/3 of median",c:"1/2 of median",d:"Equal parts",ans:"A",diff:"Advanced"},
  {q:"The circumcenter of a triangle is equidistant from all vertices. This is used to find?",a:"Circumradius",b:"Inradius",c:"Altitude",d:"Median",ans:"A",diff:"Advanced"},
  {q:"In a triangle the sum of distances from centroid to vertices: what fraction of sum of medians?",a:"2/3",b:"1/3",c:"1",d:"1/2",ans:"A",diff:"Advanced"},
  {q:"For any triangle centroid G divides OH (Euler line) such that OG:GH = ?",a:"1:2",b:"2:1",c:"1:3",d:"1:1",ans:"A",diff:"Advanced"}
],
19: [
  {q:"Two triangles are congruent if they have exactly the same?",a:"Shape and size",b:"Only shape",c:"Only size",d:"Same area",ans:"A",diff:"Easy"},
  {q:"SSS congruence criterion means?",a:"Three sides equal",b:"Two sides one angle",c:"Three angles",d:"Two angles one side",ans:"A",diff:"Easy"},
  {q:"SAS congruence criterion means?",a:"Two sides and included angle",b:"Two sides any angle",c:"Side angle side from different positions",d:"Three sides",ans:"A",diff:"Easy"},
  {q:"Two triangles are similar if they have?",a:"Same shape (equiangular)",b:"Same size",c:"Equal perimeters",d:"Equal areas",ans:"A",diff:"Easy"},
  {q:"AA similarity criterion: if two angles of one triangle equal two angles of another then?",a:"Triangles are similar",b:"Triangles are congruent",c:"Only one pair must match",d:"Cannot conclude",ans:"A",diff:"Easy"},
  {q:"In similar triangles ratio of sides = ratio of?",a:"Corresponding sides",b:"Areas directly",c:"Perimeters squared",d:"Angles",ans:"A",diff:"Easy"},
  {q:"If triangles are similar with scale factor k ratio of areas = ?",a:"k^2",b:"k",c:"k^3",d:"1/k",ans:"A",diff:"Easy"},
  {q:"RHS congruence criterion applies to?",a:"Right triangles only",b:"All triangles",c:"Isosceles only",d:"Equilateral only",ans:"A",diff:"Easy"},
  {q:"ASA congruence: two angles and?",a:"Included side",b:"Any side",c:"Hypotenuse",d:"Opposite side",ans:"A",diff:"Easy"},
  {q:"AAS congruence: two angles and?",a:"Non-included side",b:"Included side",c:"Any side",d:"Hypotenuse",ans:"A",diff:"Easy"},
  {q:"If two triangles are congruent their areas are?",a:"Equal",b:"In ratio 2:1",c:"Cannot compare",d:"One double the other",ans:"A",diff:"Easy"},
  {q:"Similar triangles have equal?",a:"Angles",b:"Side lengths",c:"Perimeters",d:"Areas",ans:"A",diff:"Easy"},
  {q:"In a triangle DE parallel to BC where D on AB E on AC. Triangle ADE is similar to?",a:"Triangle ABC",b:"Triangle DBC",c:"Triangle EBC",d:"Triangle BEC",ans:"A",diff:"Easy"},
  {q:"Scale factor between two similar triangles is 3:4. Ratio of their perimeters?",a:"3:4",b:"9:16",c:"27:64",d:"1:1",ans:"A",diff:"Easy"},
  {q:"Congruence symbol is?",a:"≅",b:"~",c:"=",d:"≈",ans:"A",diff:"Easy"},
  {q:"Triangles ABC and DEF similar with AB:DE=2:3. BC=8 cm. EF=?",a:"12 cm",b:"6 cm",c:"9 cm",d:"15 cm",ans:"A",diff:"Medium"},
  {q:"In similar triangles ratio of areas = 4:9. Ratio of corresponding sides?",a:"2:3",b:"4:9",c:"16:81",d:"1:1",ans:"A",diff:"Medium"},
  {q:"A vertical pole 12m casts shadow 8m. Building casts 20m shadow. Height of building?",a:"30 m",b:"24 m",c:"36 m",d:"15 m",ans:"A",diff:"Medium"},
  {q:"Triangle ABC with DE parallel to BC. AD:DB=3:2 and DE=6. BC=?",a:"10",b:"9",c:"12",d:"15",ans:"A",diff:"Medium"},
  {q:"Basic Proportionality Theorem (BPT): if DE parallel to BC then AD/DB =?",a:"AE/EC",b:"AB/AC",c:"DE/BC",d:"AE/AC",ans:"A",diff:"Medium"},
  {q:"Converse of BPT: if AD/DB = AE/EC then DE is?",a:"Parallel to BC",b:"Perpendicular to BC",c:"Equal to BC",d:"Bisecting BC",ans:"A",diff:"Medium"},
  {q:"In triangle ABC, angle A = angle D, angle B = angle E. AB:DE = 3:5. If BC=15 find EF.",a:"25",b:"9",c:"20",d:"30",ans:"A",diff:"Medium"},
  {q:"By SAS similarity: two sides in ratio and?",a:"Included angle equal",b:"Any angle equal",c:"Any side equal",d:"Area equal",ans:"A",diff:"Medium"},
  {q:"Pythagoras theorem: In right triangle a^2+b^2=c^2 is a consequence of?",a:"AA similarity",b:"SSS congruence",c:"RHS congruence",d:"SAS congruence",ans:"A",diff:"Medium"},
  {q:"Median bisects area: triangle ABD has area = triangle ACD. D is?",a:"Midpoint of BC",b:"Centroid",c:"Foot of altitude",d:"Incenter",ans:"A",diff:"Medium"},
  {q:"Two isosceles triangles with equal vertex angles are?",a:"Similar",b:"Congruent",c:"Equal in area",d:"Cannot conclude",ans:"A",diff:"Medium"},
  {q:"In right triangle altitude to hypotenuse creates two triangles each similar to?",a:"The original and to each other",b:"Only original",c:"Only each other",d:"Equilateral triangle",ans:"A",diff:"Medium"},
  {q:"For triangle with sides 3 4 5 and a similar triangle with scale 2, sides are?",a:"6 8 10",b:"5 6 7",c:"9 16 25",d:"6 8 12",ans:"A",diff:"Medium"},
  {q:"If two triangles are similar and one has perimeter 30 other 45 scale factor?",a:"2:3",b:"30:45",c:"Both same",d:"4:9",ans:"A",diff:"Medium"},
  {q:"Angle bisector theorem: angle bisector from A divides BC in ratio?",a:"AB:AC",b:"AC:AB",c:"AB:BC",d:"AC:BC",ans:"A",diff:"Medium"},
  {q:"Three triangles similar to each other by AA each pair. A is equiangular to B B to C. Is A similar to C?",a:"Yes (transitive)",b:"No",c:"Only if same scale",d:"Cannot determine",ans:"A",diff:"Hard"},
  {q:"In trapezoid ABCD with AB||CD. Diagonals intersect at P. Triangles APB and CPD are?",a:"Similar",b:"Congruent",c:"Equal area",d:"Right triangles",ans:"A",diff:"Hard"},
  {q:"Scale factor k=3/4. Area of smaller triangle=36. Area of larger?",a:"64",b:"48",c:"54",d:"72",ans:"A",diff:"Hard"},
  {q:"BPT proof uses concept of?",a:"Equal areas of triangles with same base",b:"Similar triangles",c:"Congruence",d:"Pythagoras",ans:"A",diff:"Hard"},
  {q:"In right triangle ABC (C=90) altitude CD to AB. Prove BC^2 = AB*BD using?",a:"AA similarity",b:"SSS",c:"SAS",d:"RHS",ans:"A",diff:"Hard"},
  {q:"Midpoint theorem: line joining midpoints of two sides is parallel to third and?",a:"Half the length",b:"Equal length",c:"Double the length",d:"Perpendicular to it",ans:"A",diff:"Hard"},
  {q:"Area of similar triangles with sides ratio p:q = ?",a:"p^2:q^2",b:"p:q",c:"p^3:q^3",d:"p^2q:q^2p",ans:"A",diff:"Hard"},
  {q:"Triangle ABC with D on AB E on AC such that area of ADE: area of BCED = 1:3. AD:DB=?",a:"1:1",b:"1:2",c:"1:3",d:"2:3",ans:"A",diff:"Hard"},
  {q:"CPCT means?",a:"Corresponding parts of congruent triangles are equal",b:"Congruent pairs in common triangles",c:"Circle properties congruent",d:"Consecutive proportional corresponding terms",ans:"A",diff:"Hard"},
  {q:"Two equilateral triangles are always?",a:"Similar",b:"Congruent",c:"Neither",d:"Similar only if same perimeter",ans:"A",diff:"Hard"},
  {q:"If two similar triangles have areas 25 and 64 their corresponding altitudes ratio?",a:"5:8",b:"25:64",c:"5:6",d:"8:5",ans:"A",diff:"Hard"},
  {q:"In triangle ABC angle bisector AD where D on BC. If AB=4 AC=6 BC=10 then BD=?",a:"4",b:"5",c:"6",d:"3",ans:"A",diff:"Advanced"},
  {q:"Converse of Pythagoras: if a^2+b^2=c^2 triangle is?",a:"Right-angled at C",b:"Acute",c:"Obtuse",d:"Equilateral",ans:"A",diff:"Advanced"},
  {q:"Two similar triangles sides ratio 3:5. Area of larger is 250. Area of smaller?",a:"90",b:"75",c:"150",d:"50",ans:"A",diff:"Advanced"},
  {q:"In similar triangles with ratio k perimeters ratio = k areas ratio = k^2 volumes(if 3D) = k^3. True?",a:"Yes",b:"Only for k>1",c:"Only for k<1",d:"Never",ans:"A",diff:"Advanced"},
  {q:"Prove: diagonal of square divides it into two congruent right isosceles triangles using?",a:"SAS congruence",b:"ASA",c:"SSS",d:"RHS",ans:"A",diff:"Advanced"},
  {q:"If triangles ABC and PQR are similar with AB corresponding to PQ ratio = 2:3. BC=10 QR=?",a:"15",b:"6.67",c:"20",d:"12",ans:"A",diff:"Advanced"},
  {q:"For BPT to hold the line must be?",a:"Parallel to the third side",b:"Perpendicular to the third side",c:"A median",d:"An altitude",ans:"A",diff:"Advanced"},
  {q:"Similarity and congruence: congruent triangles are similar with scale factor?",a:"1",b:"0",c:"2",d:"Depends on triangle",ans:"A",diff:"Advanced"},
  {q:"In trapezoid ABCD AB=CD=5 BC=8 AD=6. Triangles formed by diagonals at their intersection are?",a:"Similar to each other and to the trapezoid triangles",b:"Congruent",c:"Equilateral",d:"Right triangles",ans:"A",diff:"Advanced"},
  {q:"Ratio of areas of two similar figures with corresponding dimensions 4cm and 6cm?",a:"4:9",b:"2:3",c:"16:36",d:"8:27",ans:"A",diff:"Advanced"}
],
20: [
  {q:"Angle in a semicircle is always?",a:"90 degrees",b:"180 degrees",c:"60 degrees",d:"45 degrees",ans:"A",diff:"Easy"},
  {q:"Equal chords subtend equal angles at?",a:"Centre",b:"Circumference",c:"Other chord",d:"Tangent",ans:"A",diff:"Easy"},
  {q:"Angle subtended by chord at center vs circumference: center angle = ?",a:"2 times circumference angle",b:"Equal",c:"Half circumference angle",d:"90 degrees",ans:"A",diff:"Easy"},
  {q:"Tangent to a circle is perpendicular to?",a:"Radius at point of contact",b:"Chord",c:"Diameter",d:"Another tangent",ans:"A",diff:"Easy"},
  {q:"Length of tangents from external point to a circle are?",a:"Equal",b:"Different",c:"Sum = diameter",d:"Double radius",ans:"A",diff:"Easy"},
  {q:"Diameter is the longest chord of a circle?",a:"True",b:"False",c:"Only if circle is large",d:"Equal to radius",ans:"A",diff:"Easy"},
  {q:"Sum of opposite angles of a cyclic quadrilateral = ?",a:"180 degrees",b:"360 degrees",c:"90 degrees",d:"270 degrees",ans:"A",diff:"Easy"},
  {q:"Perpendicular from centre to a chord?",a:"Bisects the chord",b:"Doubles the chord",c:"Is tangent to chord",d:"Creates equal arcs",ans:"A",diff:"Easy"},
  {q:"Angle in same segment subtended by same arc are?",a:"Equal",b:"Supplementary",c:"Complementary",d:"Double",ans:"A",diff:"Easy"},
  {q:"If two chords intersect inside circle: PA*PB=?",a:"PC*PD",b:"PA+PB",c:"2*radius",d:"Diameter squared",ans:"A",diff:"Easy"},
  {q:"Tangent from point P to circle with center O. OP perpendicular to?",a:"Tangent at point of contact",b:"Chord",c:"Another radius",d:"Diameter",ans:"A",diff:"Easy"},
  {q:"A chord divides circle into two?",a:"Segments",b:"Sectors",c:"Arcs only",d:"Diameters",ans:"A",diff:"Easy"},
  {q:"An inscribed angle is formed by?",a:"Two chords meeting at circumference",b:"Radius and tangent",c:"Two tangents",d:"Two radii",ans:"A",diff:"Easy"},
  {q:"If chord AB subtends 60 degrees at centre angle at any point on major arc = ?",a:"30 degrees",b:"60 degrees",c:"120 degrees",d:"90 degrees",ans:"A",diff:"Easy"},
  {q:"Number of tangents from an external point to a circle?",a:"2",b:"1",c:"0",d:"Infinite",ans:"A",diff:"Easy"},
  {q:"In circle two chords PQ and RS intersect at T inside. PT=3 TQ=4 RT=6. TS=?",a:"2",b:"3",c:"4",d:"8",ans:"A",diff:"Medium"},
  {q:"Tangent PT and chord PQ. Angle TPQ=50 degrees. Angle in alternate segment = ?",a:"50 degrees",b:"40 degrees",c:"90 degrees",d:"130 degrees",ans:"A",diff:"Medium"},
  {q:"From external point two tangents of length 12 cm each distance from point to centre = 13 cm. Radius?",a:"5 cm",b:"12 cm",c:"7 cm",d:"8 cm",ans:"A",diff:"Medium"},
  {q:"Angle subtended by arc = 120 degrees at centre. Angle at any point on major arc?",a:"60 degrees",b:"120 degrees",c:"240 degrees",d:"30 degrees",ans:"A",diff:"Medium"},
  {q:"Two circles intersect. Common chord subtends angle 60 at each centre. Prove centres and chord form?",a:"Equilateral or isosceles triangle",b:"Right triangle",c:"Scalene triangle",d:"Cannot conclude",ans:"A",diff:"Medium"},
  {q:"Cyclic quadrilateral ABCD. Angle A=80. Angle C=?",a:"100",b:"80",c:"180",d:"260",ans:"A",diff:"Medium"},
  {q:"Angle in minor segment is?",a:"Obtuse",b:"Acute",c:"Right",d:"180 degrees",ans:"A",diff:"Medium"},
  {q:"Length of tangent from point (5,0) to circle x^2+y^2=9?",a:"4",b:"3",c:"5",d:"sqrt(34)",ans:"A",diff:"Medium"},
  {q:"Two concentric circles radii 5 and 13. Chord of outer tangent to inner. Length?",a:"24",b:"12",c:"10",d:"26",ans:"A",diff:"Medium"},
  {q:"Chord AB = 16 cm. Distance from centre = 6 cm. Radius?",a:"10 cm",b:"8 cm",c:"12 cm",d:"14 cm",ans:"A",diff:"Medium"},
  {q:"Secant-tangent from external point: tangent^2 = ?",a:"Secant*(external segment of secant)",b:"Chord^2",c:"Radius^2",d:"Diameter*chord",ans:"A",diff:"Medium"},
  {q:"If inscribed angle = 45 degrees then arc it subtends = ?",a:"90 degrees",b:"45 degrees",c:"180 degrees",d:"135 degrees",ans:"A",diff:"Medium"},
  {q:"Angle between two tangents from external point P: if angle between radii to contact points = 120 angle P = ?",a:"60 degrees",b:"120 degrees",c:"30 degrees",d:"90 degrees",ans:"A",diff:"Medium"},
  {q:"Equal chords are equidistant from?",a:"Centre",b:"Circumference",c:"Tangent",d:"Other chords",ans:"A",diff:"Medium"},
  {q:"In a cyclic quadrilateral exterior angle = ?",a:"Opposite interior angle",b:"Adjacent interior angle",c:"Sum of all other angles",d:"90 degrees",ans:"A",diff:"Medium"},
  {q:"PA and PB tangents from P. AB is chord. Angle APB=40. Angle AOB=?",a:"140",b:"40",c:"180",d:"70",ans:"A",diff:"Hard"},
  {q:"Chord PQ = Chord RS in same circle. Distance from O to PQ = distance from O to RS. Prove PQ=RS using?",a:"Congruent triangles",b:"Similar triangles",c:"Pythagoras",d:"Tangent theorem",ans:"A",diff:"Hard"},
  {q:"Tangent at A. Chord AB. Angle between tangent and chord = 35 degrees. Angle in alternate segment = ?",a:"35 degrees",b:"55 degrees",c:"70 degrees",d:"145 degrees",ans:"A",diff:"Hard"},
  {q:"Two tangents from P touch at A and B. PA=12. OP=13. Angle APO=?",a:"sin(APO)=12/13 so angle APO = 67.38 approx",b:"30 degrees",c:"60 degrees",d:"45 degrees",ans:"A",diff:"Hard"},
  {q:"From external point P two secants PAB and PCD. PA=4 AB=5 PC=3. CD=?",a:"9",b:"6",c:"8",d:"5",ans:"A",diff:"Hard"},
  {q:"Angle between tangent and radius is 90. Use this to find tangent length from (7,0) to circle radius 5 centre (0,0)?",a:"sqrt(49-25)=sqrt(24)=2*sqrt(6)",b:"sqrt(74)",c:"2",d:"12",ans:"A",diff:"Hard"},
  {q:"Cyclic quadrilateral ABCD. Diagonal AC bisects angle A. AB/AD = ?",a:"BC/CD",b:"AB/CD",c:"AC/BD",d:"1",ans:"A",diff:"Hard"},
  {q:"Two chords intersect at P. Segments 4 and x on one; 3 and 12 on other. x=?",a:"9",b:"6",c:"4",d:"16",ans:"A",diff:"Hard"},
  {q:"An angle inscribed in semicircle = 90. Converse: if angle = 90 the hypotenuse is?",a:"Diameter",b:"Chord",c:"Tangent",d:"Radius",ans:"A",diff:"Hard"},
  {q:"Ptolemy's theorem for cyclic quadrilateral ABCD: AC*BD = ?",a:"AB*CD + AD*BC",b:"AB*BC + CD*AD",c:"AC+BD",d:"Area of quadrilateral",ans:"A",diff:"Hard"},
  {q:"Chord at distance d from centre in circle radius r. Half-chord = ?",a:"sqrt(r^2-d^2)",b:"r-d",c:"sqrt(r^2+d^2)",d:"d",ans:"A",diff:"Advanced"},
  {q:"Radical axis of two circles is the locus of points with?",a:"Equal power w.r.t. both circles",b:"Equal distances to both centres",c:"Equal tangent lengths to both",d:"Both b and c",ans:"D",diff:"Advanced"},
  {q:"Power of a point P with respect to circle x^2+y^2=r^2: for P=(x0,y0) power=?",a:"x0^2+y0^2-r^2",b:"x0^2+y0^2+r^2",c:"r^2-x0^2-y0^2",d:"x0*y0-r^2",ans:"A",diff:"Advanced"},
  {q:"Tangent from P(5,0) to circle x^2+y^2=16 length=?",a:"3",b:"4",c:"5",d:"sqrt(41)",ans:"A",diff:"Advanced"},
  {q:"If ABCD cyclic and AB || CD then arc AD = arc BC. This makes ABCD?",a:"Isosceles trapezoid",b:"Rectangle",c:"Parallelogram",d:"Rhombus",ans:"A",diff:"Advanced"},
  {q:"Two circles external to each other. Number of common tangents?",a:"4",b:"3",c:"2",d:"1",ans:"A",diff:"Advanced"},
  {q:"Two circles internally tangent. Number of common tangents?",a:"1",b:"2",c:"3",d:"0",ans:"A",diff:"Advanced"},
  {q:"Nine-point circle of a triangle passes through midpoints and is related to circumcircle by radius factor?",a:"1/2",b:"1/3",c:"2",d:"1/4",ans:"A",diff:"Advanced"},
  {q:"Simson line: from a point P on circumcircle perpendiculars to all three sides are?",a:"Collinear",b:"Concurrent",c:"Parallel",d:"Equal",ans:"A",diff:"Advanced"},
  {q:"Chord AB subtends angle x at circumference on major arc. Angle on minor arc = ?",a:"180-x",b:"x",c:"90-x",d:"2x",ans:"A",diff:"Advanced"}
],
